# (c) https://github.com/MontiCore/monticore

stages:
- linux

TestGAN:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/gans/mnist-infogan/gans_mxnet:latest
  script: 
  - cd gluon/.test
  - chmod +x build.sh
  - ./build.sh
  except:
    changes:
    - README.md