/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.TransmissionCostsTagSchema;

import de.monticore.CommonModelingLanguage;
import de.monticore.lang.tagging._symboltable.TagableModelingLanguage;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class TransmissionCostsTagSchema {

  protected static TransmissionCostsTagSchema instance = null;

  protected TransmissionCostsTagSchema() {}

  protected static TransmissionCostsTagSchema getInstance() {
    if (instance == null) {
      instance = new TransmissionCostsTagSchema();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TagableModelingLanguage modelingLanguage) {
    // all ModelingLanguage instances are actually instances of CommonModelingLanguage
    if(modelingLanguage instanceof CommonModelingLanguage) {
      CommonModelingLanguage commonModelingLanguage = (CommonModelingLanguage)modelingLanguage;

      modelingLanguage.addTagSymbolCreator(new TransCostCmpInstSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(TransCostCmpInstSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new TransCostCmpSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(TransCostCmpSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new TransCostConnSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(TransCostConnSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new TransCostPortSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(TransCostPortSymbol.KIND));
    }
  }

  public static void registerTagTypes(TagableModelingLanguage modelingLanguage) {
    getInstance().doRegisterTagTypes(modelingLanguage);
  }
}