/**
 * (c) https://github.com/MontiCore/monticore
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/* (c) https://github.com/MontiCore/monticore */
/* generated by template symboltable.ModelingLanguage*/




package de.monticore.lang.embeddedmontiarc.embeddedmontiarcmath._symboltable;

import de.monticore.ModelingLanguageFamily;
import de.monticore.lang.embeddedmontiarc.embeddedmontiarc._symboltable.EmbeddedMontiArcLanguage;
import de.monticore.lang.embeddedmontiarcdynamic.embeddedmontiarcdynamic._symboltable.EmbeddedMontiArcDynamicLanguage;
import de.monticore.lang.embeddedmontiarcdynamic.event._symboltable.EventLanguage;
import de.monticore.lang.math._symboltable.MathLanguage;
import de.monticore.lang.mathopt._symboltable.MathOptLanguage;
import de.monticore.lang.monticar.enumlang._symboltable.EnumLangLanguage;
import de.monticore.lang.monticar.stream._symboltable.StreamLanguage;
import de.monticore.lang.monticar.streamunits._symboltable.StreamUnitsLanguage;
import de.monticore.lang.monticar.struct._symboltable.StructLanguage;

public class EmbeddedMontiArcMathLanguageFamiliy extends ModelingLanguageFamily {

  public EmbeddedMontiArcMathLanguageFamiliy() {
    addModelingLanguage(new EmbeddedMontiArcMathLanguage());
    addModelingLanguage(new MathOptLanguage());
    addModelingLanguage(new StreamLanguage());
    addModelingLanguage(new StructLanguage());
    addModelingLanguage(new StreamUnitsLanguage());
    addModelingLanguage(new EnumLangLanguage());
    addModelingLanguage(new EventLanguage());
    addModelingLanguage(new MathLanguage());
  }
}
