/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simulator_integration_HardwareEmulatorInterface */

#ifndef _Included_simulator_integration_HardwareEmulatorInterface
#define _Included_simulator_integration_HardwareEmulatorInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_simulator_integration_HardwareEmulatorInterface_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    alloc_autopilot
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_simulator_integration_HardwareEmulatorInterface_alloc_1autopilot
  (JNIEnv *, jobject, jstring);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    free_autopilot
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_HardwareEmulatorInterface_free_1autopilot
  (JNIEnv *, jobject, jint);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    start_tick
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_HardwareEmulatorInterface_start_1tick
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    end_tick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_simulator_integration_HardwareEmulatorInterface_end_1tick
  (JNIEnv *, jobject);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    querry
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simulator_integration_HardwareEmulatorInterface_querry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    querry_autopilot
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_simulator_integration_HardwareEmulatorInterface_querry_1autopilot
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    add_one_input
 * Signature: (ILjava/lang/String;Ljava/io/Serializable;)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_HardwareEmulatorInterface_add_1one_1input
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     simulator_integration_HardwareEmulatorInterface
 * Method:    querry_outputs
 * Signature: (ILjava/util/HashMap;)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_HardwareEmulatorInterface_querry_1outputs
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
