/* generated by template symboltable.ModelingLanguage*/




package weather._symboltable;

import java.util.Optional;
import weather._parser.WeatherParser;
import de.monticore.symboltable.MutableScope;
import de.monticore.symboltable.ResolvingConfiguration;

public abstract class WeatherLanguage extends de.monticore.CommonModelingLanguage {

  public WeatherLanguage(String langName, String fileEnding) {
    super(langName, fileEnding);

    initResolvingFilters();
  }

  @Override
  public WeatherParser getParser() {
    return new WeatherParser();
  }


  @Override
  public WeatherModelLoader getModelLoader() {
    return (WeatherModelLoader) super.getModelLoader();
  }

  
  @Override
  protected WeatherModelLoader provideModelLoader() {
    return new WeatherModelLoader(this);
  }
  

  protected void initResolvingFilters() {
  }
}
