/* generated by template symboltable.ModelLoader*/




package weather._symboltable;

import de.monticore.symboltable.MutableScope;
import de.monticore.symboltable.ResolvingConfiguration;


public class WeatherModelLoader extends de.monticore.modelloader.ModelingLanguageModelLoader<weather._ast.ASTTemperature> {

  public WeatherModelLoader(WeatherLanguage language) {
    super(language);
  }

  @Override
  protected void createSymbolTableFromAST(final weather._ast.ASTTemperature ast, final String modelName,
    final MutableScope enclosingScope, final ResolvingConfiguration resolvingConfiguration) {
  }

  @Override
  public WeatherLanguage getModelingLanguage() {
    return (WeatherLanguage) super.getModelingLanguage();
  }
}
