version: '{build}'
skip_tags: true
clone_folder: C:\EMAStudioBuilder
clone_depth: 10
platform:
  - x64
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      
      # download new dependencies if dependencies.txt has changed
      if(![System.IO.File]::Exists('C:\dependencies')){
        New-Item -ItemType directory -Path C:\dependencies\EmbeddedMontiArcStudio
        Set-Location -Path C:\dependencies 
        
        # get links from dependencies.txt
        Get-Content C:\EMAStudioBuilder\dependencies.txt | Where-Object {$_ -match '^\*\*.+'} | ForEach-Object {
            $link = $_.Remove(0,3)
            
            # if it is a zip download and extract
            if($link -match '[a-zA-Z0-9\-\.]+\.zip'){
              $filename = $matches[0]
              "Downloading " + $filename + " from: " + $link
              appveyor DownloadFile $link -FileName $filename
              "Extracting " + $filename + " to " + "C:\dependencies\EmbeddedMontiArcStudio"
              [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\dependencies\EmbeddedMontiArcStudio\" + $filename, 'C:\EMAStudioBuilder\EmbeddedMontiArcStudio')
              
          }
        }
      }
      
cache:
  - C:\dependencies -> dependencies.txt
