version: '{build}'
skip_tags: true
clone_folder: C:\EMAStudioBuilder
clone_depth: 10
platform:
  - x64
install:
  - ps: |
      if(![System.IO.File]::Exists('C:\dependencies')){
        New-Item -ItemType directory -Path C:\dependencies
        Set-Location -Path C:\dependencies 
        tree /F
        foreach($link in Get-Content C:\EMAStudioBuilder\dependencies.txt) {
          if($link -match '^\*\*.+'){
            $link.Remove(0,3)
            if($link -match '[a-zA-Z0-9\-]+\.zip'){
              $filename = matches[1]
              "Downloading " + $filename + " from: " + $link
              appveyor DownloadFile $line -FileName $filename
              "Extracting " + $filename
              [System.IO.Compression.ZipFile]::ExtractToDirectory($filename, 'C:\EMAStudioBuilder\EMAStudio')
            }
            
          }
        }
        tree /F
      }
      
cache:
  - C:\dependencies -> dependencies.txt
