#pragma once

#include <string>



#define BASIC_INTERFACE_INPUT_COUNT 9
#define BASIC_INTERFACE_OUTPUT_COUNT 3
#define BASIC_INTERFACE_PORT_COUNT (BASIC_INTERFACE_INPUT_COUNT+BASIC_INTERFACE_OUTPUT_COUNT)

extern std::string BASIC_INTERFACE;

#define PORT_TRUE_VELOCITY 0
#define PORT_TRUE_POSITION 1
#define PORT_TRUE_COMPASS 2
#define PORT_TRAJ_LENGTH 3
#define PORT_TRAJ_X 4
#define PORT_TRAJ_Y 5
#define PORT_STEERING 6
#define PORT_GAS 7
#define PORT_BRAKING 8
#define PORT_SET_STEERING 9
#define PORT_SET_GAS 10
#define PORT_SET_BRAKING 11