URL: https://git.rwth-aachen.de/
SourceToken: glpat-1E9aKZussdM6-vaqwDGk
TargetToken: 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
Repos:
  - 25225
  - 17712
SourceUser: David.Blum
TargetRepoOwner: DavidBlm