FROM registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow

RUN apt-get update --allow-releaseinfo-change

# install maven and tensorflow for python3
RUN apt-get install -y apt-utils maven
RUN pip3 install protobuf==3.19.4
RUN pip3 install tensorflow==1.13.1 protobuf==3.19.4
RUN apt-get -y autoremove

# install onnx related dependencies
RUN apt-get install -y libprotobuf-dev protobuf-compiler
RUN export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON" && pip3 install onnx==1.2.1 onnxmltools==1.10.0 keras2onnx==1.7.0
