# (c) https://github.com/MontiCore/monticore  
stages:
- project
- adapter
- deploy

BranchJobDeploy:
  stage: deploy
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2someip
  script:
    - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean deploy --settings settings.xml
    - cat target/site/jacoco/index.html
  only:
    - master

BranchJobProject:
  stage: project
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2someip
  script:
  - mvn clean install -s settings.xml
  except:
  - master

BranchJobAdapter:
  stage: adapter
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2someip
  script:
  - cd someip_adapter
  - cmake .
  - make
  except:
  - master

