/* (c) https://github.com/MontiCore/monticore */
/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.embeddedmontiarc.embeddedmontiarc._symboltable.cncModel;

public class EMAConnectorKind
        implements de.monticore.symboltable.SymbolKind {

  public static final EMAConnectorKind INSTANCE = new EMAConnectorKind();

  protected EMAConnectorKind() {
  }

}
