/**
 *
 *  ******************************************************************************
 *  MontiCAR Modeling Family, www.se-rwth.de
 *  Copyright (c) 2017, Software Engineering Group at RWTH Aachen,
 *  All rights reserved.
 *
 *  This project is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3.0 of the License, or (at your option) any later version.
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this project. If not, see <http://www.gnu.org/licenses/>.
 * *******************************************************************************
 */
/* generated by template symboltable.ModelingLanguage*/




package de.monticore.lang.embeddedmontiarc.application._symboltable;

import de.monticore.ModelingLanguageFamily;
import de.monticore.lang.application.application._symboltable.ApplicationLanguage;
import de.monticore.lang.embeddedmontiarc.embeddedmontiarc._symboltable.EmbeddedMontiArcLanguage;

public class EmbeddedMontiArcApplicationLanguageFamiliy extends ModelingLanguageFamily {

  public EmbeddedMontiArcApplicationLanguageFamiliy() {
    addModelingLanguage(new EmbeddedMontiArcLanguage());
    addModelingLanguage(new ApplicationLanguage());
  }
}
