# (c) https://github.com/MontiCore/monticore
stages:
  - linux

TestCoraCustomNetwork:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
  - ln /usr/bin/python3 /usr/bin/python -f
  - python -m pip install -U pip
  - python -m pip install scikit-image
  - python -m pip install opencv-python
  - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
  - cd cora-custom-gnn
  - mvn dependency:resolve emadl:train -s settings.xml -U

TestCoraDglNetwork:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1
  script:
  - ln /usr/bin/python3 /usr/bin/python -f
  - python -m pip install -U pip
  - python -m pip install scikit-image
  - python -m pip install opencv-python
  - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
  - export DGLBACKEND=mxnet
  - cd cora-dgl-gnn
  - mvn dependency:resolve emadl:train -s settings.xml -U

TestCuboidDglNetwork:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1
  script:
  - ln /usr/bin/python3 /usr/bin/python -f
  - python -m pip install -U pip
  - python -m pip install scikit-image
  - python -m pip install opencv-python
  - mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
  - export DGLBACKEND=mxnet
  - cd cuboid-dgl-gnn
  - mvn dependency:resolve emadl:train -s settings.xml -U

