# (c) https://github.com/MontiCore/monticore  
 stages:
 - linux
# - windows


 masterJobLinux:
   stage: linux
   image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcdynamics/z3
   script:
   - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
   - mvn package sonar:sonar -s settings.xml
   only:
   - master

 BranchJobLinux:
   stage: linux
   image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcdynamics/z3
   script:
   - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
   except:
   - master


# masterJobWindows:
#   stage: windows
#   script:
#   - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
#   tags:
#   - Windows10_OS
#
#
