/* (c) https://github.com/MontiCore/monticore */
/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.embeddedmontiview.embeddedmontiview._symboltable;

public class EMAEffectorKind
    implements de.monticore.symboltable.SymbolKind {

  public static final EMAEffectorKind INSTANCE = new EMAEffectorKind();

  protected EMAEffectorKind() {
  }

}
