/* (c) https://github.com/MontiCore/monticore */
/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.embeddedmontiview.embeddedmontiview._symboltable;

import de.monticore.symboltable.SymbolKind;

public class EmbeddedPortKind implements SymbolKind {

  public static final EmbeddedPortKind INSTANCE = new EmbeddedPortKind();

  protected EmbeddedPortKind() {
  }

}
