/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTMapOverlap;

public interface SimulationASTMapOverlapCoCo {
  public void check(ASTMapOverlap node);
}
