/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTMapSectorHeight;

public interface SimulationASTMapSectorHeightCoCo {
  public void check(ASTMapSectorHeight node);
}
