/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTSimulationRenderFrequency;

public interface SimulationASTSimulationRenderFrequencyCoCo {
  public void check(ASTSimulationRenderFrequency node);
}
