/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTSimulationType;

public interface SimulationASTSimulationTypeCoCo {
  public void check(ASTSimulationType node);
}
