/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTPedestrians;

public interface SimulationASTPedestriansCoCo {
  public void check(ASTPedestrians node);
}
