/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTFixedWeather;

public interface SimulationASTFixedWeatherCoCo {
  public void check(ASTFixedWeather node);
}
