/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTMaxSectorUsers;

public interface SimulationASTMaxSectorUsersCoCo {
  public void check(ASTMaxSectorUsers node);
}
