/* generated by template cocos.CoCoInterface*/



package simulation._cocos;

import simulation._ast.ASTForecast;

public interface SimulationASTForecastCoCo {
  public void check(ASTForecast node);
}
