/* (c) https://github.com/MontiCore/monticore */
#include "armadillo"
#include <iosfwd>
#include <string>
#include <cstdint>
#include <vector>
#include <memory>
#include <cstddef>
#include <sstream>
#include <type_traits>
#include <utility>
#include <tuple>
#include <ctime>
#include <ratio>
#include <chrono>
#include <ostream>
#include <signal.h>
#include <exception>
#include <stdexcept>
#include <streambuf>
#include <fstream>
#include <map>
#include <set>
#include <algorithm>
#include <cstring>
#include <cfloat>
#include <cstdio>
#include <assert.h>
#include <cmath>
#include <limits>
#include <cassert>
//#include <AfxWin.h>
#include <windows.h>
#include <unistd.h>
#include <stdbool.h>
#include <sys/types.h>
//#include <sys/sysctl.h>
#include <cerrno>
#include <crtdbg.h>
#include <iomanip>
#include <cstdlib>
#include <ios>
#include <iostream>
#include <cctype>

