/* generated from model Weather*/
/* generated by template ast.Class*/
// Class declaration
/* generated by template ast.ASTConstantsClass*/



package weather._ast;

import java.util.Collection;
import com.google.common.collect.Sets;

public class ASTConstantsWeather extends Object {

  public static final String LANGUAGE = "Weather";
  
  public static final int DEFAULT = 0;
  public static final int ALTOCUMULUS = 1;
  public static final int ALTOSTRATUS = 2;
  public static final int CIRROCUMULUS = 3;
  public static final int CIRROSTRATUS = 4;
  public static final int CIRRUS = 5;
  public static final int CONSTANT0 = 6;
  public static final int CONSTANT1 = 7;
  public static final int CONSTANT10 = 8;
  public static final int CONSTANT11 = 9;
  public static final int CONSTANT12 = 10;
  public static final int CONSTANT13 = 11;
  public static final int CONSTANT14 = 12;
  public static final int CONSTANT15 = 13;
  public static final int CONSTANT16 = 14;
  public static final int CONSTANT17 = 15;
  public static final int CONSTANT18 = 16;
  public static final int CONSTANT19 = 17;
  public static final int CONSTANT2 = 18;
  public static final int CONSTANT20 = 19;
  public static final int CONSTANT21 = 20;
  public static final int CONSTANT22 = 21;
  public static final int CONSTANT3 = 22;
  public static final int CONSTANT4 = 23;
  public static final int CONSTANT5 = 24;
  public static final int CONSTANT6 = 25;
  public static final int CONSTANT7 = 26;
  public static final int CONSTANT8 = 27;
  public static final int CONSTANT9 = 28;
  public static final int CONTRAILS = 29;
  public static final int CUMULONIMBUS = 30;
  public static final int DRIZZLE = 31;
  public static final int FOG = 32;
  public static final int GRAUPEL = 33;
  public static final int GUSTNADO = 34;
  public static final int HAIL = 35;
  public static final int LANDSPOUT = 36;
  public static final int MIRAGE = 37;
  public static final int NIMBOSTRATUS = 38;
  public static final int NOCTILUCENT = 39;
  public static final int NONE = 40;
  public static final int PERCENT = 41;
  public static final int RAIN = 42;
  public static final int RAINBOW = 43;
  public static final int SLEET = 44;
  public static final int SMOG = 45;
  public static final int SNAIN = 46;
  public static final int SNOW = 47;
  public static final int STRATOCUMULUS = 48;
  public static final int STRATUS = 49;
  public static final int THUNDERSTORM = 50;
  public static final int UNLIMITED = 51;
  public static final int WATERSPOUT = 52;

  /** All direct super grammars.*/
  public static String[] superGrammars = { "NumberUnit"};
  
  public static Collection<String> getAllLanguages() {
    Collection<String> allLanguages = Sets.newLinkedHashSet();
    allLanguages.addAll(numberunit._ast.ASTConstantsNumberUnit.getAllLanguages());
    allLanguages.add(LANGUAGE);
    return allLanguages;
  }

  /** Constructs a new ASTConstantsFile.*/
  public ASTConstantsWeather() {
  }

}

