/* generated from model Weather*/
/* generated by template ast.AstClass*/

package weather._ast;

/* generated by template ast_emf.AstEImports*/
import java.util.Optional;
import java.util.Iterator;
import de.se_rwth.commons.logging.Log;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;

 public  class ASTTemperature extends /* generated by template ast.AstSuperTypes*/
de.monticore.emf._ast.ASTECNode implements  ASTWeatherNode
 {
  /* generated by template ast.Attribute*/
  
   protected  String weatherTemperature;

    /* generated by template ast.Constructor*/
  
   protected  ASTTemperature (/* generated by template ast.ParametersDeclaration*/
    // Parameters declaration
 
    )  
  /* generated by template ast.EmptyMethodBody*/

  { // empty body 
  }


    /* generated by template ast.Constructor*/
  
   protected  ASTTemperature (/* generated by template ast.ConstructorParametersDeclaration*/
     String weatherTemperature 
 
    )  
  /* generated by template ast.ConstructorAttributesSetter*/
  {
    setWeatherTemperature(weatherTemperature);
  }


  
    /* generated by template ast.ClassMethod*/
  
   public  void accept(weather._visitor.WeatherVisitor visitor)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(visitor, "0xA7006_526 Parameter 'visitor' must not be null.");

     /* generated by template ast.additionalmethods.Accept*/

      visitor.handle(this);

  } 

    /* generated by template ast.ClassMethod*/
  
   public  void accept(numberunit._visitor.NumberUnitVisitor visitor)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(visitor, "0xA7006_179 Parameter 'visitor' must not be null.");

     /* generated by template ast.additionalmethods.AcceptSuper*/

    if (visitor instanceof weather._visitor.WeatherVisitor) {
      accept((weather._visitor.WeatherVisitor) visitor);      
    } else {
      de.se_rwth.commons.logging.Log.error("0xA7000_445AST node type ASTTemperature of the sub language Weather expected a visitor of type weather._visitor.WeatherVisitor, but got numberunit._visitor.NumberUnitVisitor. Visitors of a super language may not be used on ASTs containing nodes of the sub language. Use a visitor of the sub language.");
    }

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEquals(Object o,boolean forceSameOrder)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_592 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.DeepEqualsWithOrder*/

      ASTTemperature comp;
    if ((o instanceof ASTTemperature)) {
      comp = (ASTTemperature) o;
    } else {
      return false;
    }
    if (!equalAttributes(comp)) {
      return false;
    }
    return true;     


  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEquals(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_442 Parameter 'o' must not be null.");

     return deepEquals(o, true);

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEqualsWithComments(Object o,boolean forceSameOrder)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_249 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.DeepEqualsWithComments*/

      ASTTemperature comp;
    if ((o instanceof ASTTemperature)) {
      comp = (ASTTemperature) o;
    } else {
      return false;
    }
    if (!equalsWithComments(comp)) {
      return false;
    }
    return true;     

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEqualsWithComments(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_426 Parameter 'o' must not be null.");

     return deepEqualsWithComments(o, true);

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean equalAttributes(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_043 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.EqualAttributes*/

      ASTTemperature comp;
    if ((o instanceof ASTTemperature)) {
      comp = (ASTTemperature) o;
    } else {
      return false;
    }
	// comparing weatherTemperature 
    if ( (this.weatherTemperature == null && comp.weatherTemperature != null) 
      || (this.weatherTemperature != null && !this.weatherTemperature.equals(comp.weatherTemperature)) ) {
      return false;
    }
    return true;     


  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean equalsWithComments(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_833 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.EqualsWithComments*/

      ASTTemperature comp;
    if ((o instanceof ASTTemperature)) {
      comp = (ASTTemperature) o;
    } else {
      return false;
    }
    if (!equalAttributes(comp)) {
      return false;
    }
    // comparing comments
    if (get_PreComments().size() == comp.get_PreComments().size()) {
      java.util.Iterator<de.monticore.ast.Comment> one = get_PreComments().iterator();
      java.util.Iterator<de.monticore.ast.Comment> two = comp.get_PreComments().iterator();
      while (one.hasNext()) {
        if (!one.next().equals(two.next())) {
          return false;
        }
      }
    } else {
      return false;
    }
    
    if (get_PostComments().size() == comp.get_PostComments().size()) {
      java.util.Iterator<de.monticore.ast.Comment> one = get_PostComments().iterator();
      java.util.Iterator<de.monticore.ast.Comment> two = comp.get_PostComments().iterator();
      while (one.hasNext()) {
        if (!one.next().equals(two.next())) {
          return false;
        }
      }
    } else {
      return false;
    }
    return true;

  } 

    /* generated by template ast.ClassMethod*/
  
   public  java.util.Collection<de.monticore.ast.ASTNode> get_Children()   { 
     
     /* generated by template ast.additionalmethods.GetChildren*/

    java.util.LinkedList<de.monticore.ast.ASTNode> result = new java.util.LinkedList<de.monticore.ast.ASTNode>();
    return result;

  } 

    /* generated by template ast.ClassMethod*/
  
   public  void remove_Child(de.monticore.ast.ASTNode child)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(child, "0xA7006_543 Parameter 'child' must not be null.");

     /* generated by template ast.additionalmethods.RemoveChild*/


  } 

    /* generated by template ast.ClassMethod*/
  
   public  static  Builder getBuilder()   { 
     
     return new Builder();

  } 

    /* generated by template ast.ClassMethod*/
  
   public  ASTTemperature deepClone()   { 
     
     return deepClone(_construct());

  } 

    /* generated by template ast.ClassMethod*/
  
   public  ASTTemperature deepClone(ASTTemperature result)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(result, "0xA7006_677 Parameter 'result' must not be null.");

     /* generated by template ast.additionalmethods.DeepCloneWithParameters*/
  
    super.deepClone(result);
    
    result.weatherTemperature = this.weatherTemperature;
    
    return result;

  } 

    /* generated by template ast.ClassMethod*/
  
   protected  ASTTemperature _construct()   { 
     
     return new ASTTemperature();

  } 

    /* generated by template ast.ClassMethod*/
  
   public  String getWeatherTemperature()   { 
     
     /* generated by template ast.additionalmethods.Get*/

    return  this.weatherTemperature;

  } 

    /* generated by template ast.ClassMethod*/
  
   public  void setWeatherTemperature(String weatherTemperature)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(weatherTemperature, "0xA7006_067 Parameter 'weatherTemperature' must not be null.");

     /* generated by template ast_emf.additionalmethods.Set*/

    String oldWeatherTemperature = this.weatherTemperature;
    this.weatherTemperature = weatherTemperature;
    if (eNotificationRequired()) {
      eNotify(new ENotificationImpl(this, Notification.SET, WeatherPackage.ASTTemperature_WeatherTemperature, oldWeatherTemperature, weatherTemperature));
    }  

  } 

    /* generated by template ast.ClassMethod*/
  
   public  Object eGet(int featureID,boolean resolve,boolean coreType)   { 
     
     /* generated by template ast_emf.additionalmethods.EGet*/
  
    switch (featureID) {
      case WeatherPackage.ASTTemperature_WeatherTemperature:
         return getWeatherTemperature();
    }
    return eDynamicGet(featureID, resolve, coreType);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  void eSet(int featureID,Object newValue)   { 
     
     /* generated by template ast_emf.additionalmethods.ESet*/
  
    switch (featureID) {
      case WeatherPackage.ASTTemperature_WeatherTemperature:
        setWeatherTemperature((String)newValue);
        return;
    }
    eDynamicSet(featureID, newValue);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  void eUnset(int featureID)   { 
     
     /* generated by template ast_emf.additionalmethods.EUnset*/
 
    switch (featureID) {
      case WeatherPackage.ASTTemperature_WeatherTemperature:
        setWeatherTemperature(null);
      return;
    }
    eDynamicUnset(featureID);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean eIsSet(int featureID)   { 
     
     /* generated by template ast_emf.additionalmethods.EIsSet*/
 
    switch (featureID) {
      case WeatherPackage.ASTTemperature_WeatherTemperature:
        return getWeatherTemperature() != null;
    }
    return eDynamicIsSet(featureID);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  int eBaseStructuralFeatureID(int featureID,Class<?> baseClass)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(baseClass, "0xA7006_661 Parameter 'baseClass' must not be null.");

     /* generated by template ast_emf.additionalmethods.EStructuralFeature*/
  
    return super.eBaseStructuralFeatureID(featureID, baseClass);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  int eDerivedStructuralFeatureID(int featureID,Class<?> baseClass)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(baseClass, "0xA7006_482 Parameter 'baseClass' must not be null.");

     /* generated by template ast_emf.additionalmethods.EStructuralFeature*/
  
    return super.eDerivedStructuralFeatureID(featureID, baseClass);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  String toString()   { 
     
     /* generated by template ast_emf.additionalmethods.EToString*/
  
    if (eIsProxy()) {
      return super.toString();
    }
    StringBuffer result = new StringBuffer(getClass().getSimpleName());
    result.append(" WeatherTemperature: ");
    result.append(weatherTemperature);
    return result.toString();
  } 

    /* generated by template ast.ClassMethod*/
  
   protected  EClass eStaticClass()   { 
     
     return WeatherPackage.Literals.ASTTemperature;
  } 

   
  /* generated by template ast.ClassContent*/
  // Class content

    /* generated by template ast.AstBuilder*/

 /**
   * Builder for {@link ASTTemperature}.
   */
  public static class Builder  {
    /* generated by template ast.BuilderAttribute*/
     protected  String weatherTemperature;

    public ASTTemperature build() {
      return new ASTTemperature (/* generated by template ast.BuilderConstructorParametersDeclaration*/
  
        this.weatherTemperature 

      );
    }
    /* generated by template ast.AstBuilderAttributeSetter*/
    public Builder weatherTemperature(String weatherTemperature) {
      this.weatherTemperature = weatherTemperature;
      return this;
    }

  }    

  
}
