deploy-pretrained:
  image: maven:3.6-jdk-8
  script:
    - mvn emadl:deploy-pretrained -s ci_settings.xml
  only:
    - master


install-pretrained:
  image: maven:3.6-jdk-8
  script:
    - mvn emadl:install-pretrained -s ci_settings.xml
  except:
    - master
