/* generated from model Simulation*/
/* generated by template ast.Class*/
// Class declaration
/* generated by template ast.ASTConstantsClass*/



package simulation._ast;

import java.util.Collection;
import com.google.common.collect.Sets;

public class ASTConstantsSimulation extends Object {

  public static final String LANGUAGE = "Simulation";
  
  public static final int DEFAULT = 0;

  /** All direct super grammars.*/
  public static String[] superGrammars = { "Weather","SI"};
  
  public static Collection<String> getAllLanguages() {
    Collection<String> allLanguages = Sets.newLinkedHashSet();
    allLanguages.addAll(weather._ast.ASTConstantsWeather.getAllLanguages());
    allLanguages.addAll(si._ast.ASTConstantsSI.getAllLanguages());
    allLanguages.add(LANGUAGE);
    return allLanguages;
  }

  /** Constructs a new ASTConstantsFile.*/
  public ASTConstantsSimulation() {
  }

}

