/* generated from model Simulation*/
/* generated by template ast.AstInterface*/



package simulation._ast;


/* generated by template ast.ASTNodeBase*/

import de.monticore.ast.ASTNode;
import simulation._visitor.SimulationVisitor;

/**
 * Interface for all AST nodes of the Simulation language.
 */
public interface ASTSimulationNode extends ASTNode {

  public void accept(SimulationVisitor visitor);

}


