/* generated from model Simulation*/
/* generated by template ast.AstInterface*/



package simulation._ast;


/* generated by template ast_emf.EPackage*/




import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EDataType;
import de.monticore.emf._ast.ASTEPackage;

public interface SimulationPackage extends ASTEPackage {
  // The package name.
  String eNAME = "Simulation";
  // The package namespace URI.
  String eNS_URI = "http://Simulation/1.0";
  // The package namespace name.
  String eNS_PREFIX = "Simulation";
  // The singleton instance of the package.
  SimulationPackage eINSTANCE = SimulationPackageImpl.init();
  
  int ConstantsSimulation = 0;
    
  int ASTSimulation = 1;
  int ASTSimulationRenderFrequency = 2;
  int ASTSimulationLoopFrequency = 3;
  int ASTSimulationDuration = 4;
  int ASTSimulationType = 5;
  int ASTWeatherObj = 6;
  int ASTWeather = 7;
  int ASTFixedWeather = 8;
  int ASTSequenceWeather = 9;
  int ASTRandomWeather = 10;
  int ASTForecast = 11;
  int ASTTime = 12;
  int ASTMapPath = 13;
  int ASTMapName = 14;
  int ASTMapHeight = 15;
  int ASTMapOverlap = 16;
  int ASTMapSectorWidth = 17;
  int ASTMapSectorHeight = 18;
  int ASTMaxSectorUsers = 19;
  int ASTTimeout = 20;
  int ASTPedestrians = 21;
  int ASTPedestrianDensity = 22;
  int ASTVehicles = 23;
  int ASTExplicitVehicle = 24;
  int ASTPathedVehicle = 25;
  int ASTRandomVehicle = 26;
  
    /* generated by template ast.Constant*/
   int ASTSimulation_MapHeight = 0;

    /* generated by template ast.Constant*/
   int ASTSimulation_MapName = 1;

    /* generated by template ast.Constant*/
   int ASTSimulation_MapOverlap = 2;

    /* generated by template ast.Constant*/
   int ASTSimulation_MapPath = 3;

    /* generated by template ast.Constant*/
   int ASTSimulation_MapSectorHeight = 4;

    /* generated by template ast.Constant*/
   int ASTSimulation_MapSectorWidth = 5;

    /* generated by template ast.Constant*/
   int ASTSimulation_MaxSectorUsers = 6;

    /* generated by template ast.Constant*/
   int ASTSimulation_Name = 7;

    /* generated by template ast.Constant*/
   int ASTSimulation_PedestrianDensity = 8;

    /* generated by template ast.Constant*/
   int ASTSimulation_Pedestrians = 9;

    /* generated by template ast.Constant*/
   int ASTSimulation_SimulationDuration = 10;

    /* generated by template ast.Constant*/
   int ASTSimulation_SimulationLoopFrequency = 11;

    /* generated by template ast.Constant*/
   int ASTSimulation_SimulationRenderFrequency = 12;

    /* generated by template ast.Constant*/
   int ASTSimulation_SimulationType = 13;

    /* generated by template ast.Constant*/
   int ASTSimulation_Time = 14;

    /* generated by template ast.Constant*/
   int ASTSimulation_Timeout = 15;

    /* generated by template ast.Constant*/
   int ASTSimulation_Vehicles = 16;

    /* generated by template ast.Constant*/
   int ASTSimulation_Weather = 17;

    /* generated by template ast.Constant*/
   int ASTSimulationRenderFrequency_SimRenderFreq = 0;

    /* generated by template ast.Constant*/
   int ASTSimulationLoopFrequency_SimLoopFreq = 0;

    /* generated by template ast.Constant*/
   int ASTSimulationDuration_SimDuration = 0;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_ArtificialPhenomenas = 0;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Clouding = 1;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Humidity = 2;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_OpticalPhenomenas = 3;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Precipitationamount = 4;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Precipitationtype = 5;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Pressure = 6;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Sight = 7;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Temperature = 8;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_WeatherPhenomenas = 9;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Winddirection = 10;

    /* generated by template ast.Constant*/
   int ASTWeatherObj_Windstrength = 11;

    /* generated by template ast.Constant*/
   int ASTWeather_FixedWeather = 0;

    /* generated by template ast.Constant*/
   int ASTWeather_Forecast = 1;

    /* generated by template ast.Constant*/
   int ASTWeather_RandomWeather = 2;

    /* generated by template ast.Constant*/
   int ASTWeather_SequenceWeather = 3;

    /* generated by template ast.Constant*/
   int ASTFixedWeather_FixedWeatherObj = 0;

    /* generated by template ast.Constant*/
   int ASTSequenceWeather_RandomWeatherObj = 0;

    /* generated by template ast.Constant*/
   int ASTSequenceWeather_SequenceDuration = 1;

    /* generated by template ast.Constant*/
   int ASTRandomWeather_RandomDuration = 0;

    /* generated by template ast.Constant*/
   int ASTForecast_ForecastDuration = 0;

    /* generated by template ast.Constant*/
   int ASTForecast_ForecastWeatherObj = 1;

    /* generated by template ast.Constant*/
   int ASTTime_TimeHours = 0;

    /* generated by template ast.Constant*/
   int ASTTime_TimeMilliseconds = 1;

    /* generated by template ast.Constant*/
   int ASTTime_TimeMinutes = 2;

    /* generated by template ast.Constant*/
   int ASTTime_TimeSeconds = 3;

    /* generated by template ast.Constant*/
   int ASTTime_UnitNumber = 4;

    /* generated by template ast.Constant*/
   int ASTMapPath_MapPath = 0;

    /* generated by template ast.Constant*/
   int ASTMapName_MapName = 0;

    /* generated by template ast.Constant*/
   int ASTMapHeight_HeightMap = 0;

    /* generated by template ast.Constant*/
   int ASTMapOverlap_MapOverlap = 0;

    /* generated by template ast.Constant*/
   int ASTMapSectorWidth_SectorWidth = 0;

    /* generated by template ast.Constant*/
   int ASTMapSectorHeight_SectorHeight = 0;

    /* generated by template ast.Constant*/
   int ASTMaxSectorUsers_MaxSectorUsers = 0;

    /* generated by template ast.Constant*/
   int ASTTimeout_Timeout = 0;

    /* generated by template ast.Constant*/
   int ASTPedestrians_EndX = 0;

    /* generated by template ast.Constant*/
   int ASTPedestrians_EndY = 1;

    /* generated by template ast.Constant*/
   int ASTPedestrians_EndZ = 2;

    /* generated by template ast.Constant*/
   int ASTPedestrians_StartX = 3;

    /* generated by template ast.Constant*/
   int ASTPedestrians_StartY = 4;

    /* generated by template ast.Constant*/
   int ASTPedestrianDensity_PedestrianDensity = 0;

    /* generated by template ast.Constant*/
   int ASTVehicles_ExplicitVehicles = 0;

    /* generated by template ast.Constant*/
   int ASTVehicles_PathedVehicles = 1;

    /* generated by template ast.Constant*/
   int ASTVehicles_RandomVehicles = 2;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_DestX = 0;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_DestY = 1;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_DestZ = 2;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_StartRot = 3;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_StartX = 4;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_StartY = 5;

    /* generated by template ast.Constant*/
   int ASTExplicitVehicle_Vehicle = 6;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_Amount = 0;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_DestRadius = 1;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_DestX = 2;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_DestY = 3;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_SpawnRadius = 4;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_SpawnX = 5;

    /* generated by template ast.Constant*/
   int ASTPathedVehicle_SpawnY = 6;

    /* generated by template ast.Constant*/
   int ASTRandomVehicle_Amount = 0;

    /* generated by template ast.Constant*/
   int ASTRandomVehicle_DestX = 1;

    /* generated by template ast.Constant*/
   int ASTRandomVehicle_DestY = 2;

    /* generated by template ast.Constant*/
   int ASTRandomVehicle_StartX = 3;

    /* generated by template ast.Constant*/
   int ASTRandomVehicle_StartY = 4;

    
    // Returns the factory that creates the instances of the model.
  SimulationNodeFactory getSimulationFactory();
  
  EEnum getConstantsSimulation();
    
  EClass getSimulation();
  EClass getSimulationRenderFrequency();
  EClass getSimulationLoopFrequency();
  EClass getSimulationDuration();
  EClass getSimulationType();
  EClass getWeatherObj();
  EClass getWeather();
  EClass getFixedWeather();
  EClass getSequenceWeather();
  EClass getRandomWeather();
  EClass getForecast();
  EClass getTime();
  EClass getMapPath();
  EClass getMapName();
  EClass getMapHeight();
  EClass getMapOverlap();
  EClass getMapSectorWidth();
  EClass getMapSectorHeight();
  EClass getMaxSectorUsers();
  EClass getTimeout();
  EClass getPedestrians();
  EClass getPedestrianDensity();
  EClass getVehicles();
  EClass getExplicitVehicle();
  EClass getPathedVehicle();
  EClass getRandomVehicle();
    
  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MapHeight() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MapName() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MapOverlap() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MapPath() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MapSectorHeight() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MapSectorWidth() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_MaxSectorUsers() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTSimulation_Name() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_PedestrianDensity() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_Pedestrians() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_SimulationDuration() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_SimulationLoopFrequency() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_SimulationRenderFrequency() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_SimulationType() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_Time() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_Timeout() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_Vehicles() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulation_Weather() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulationRenderFrequency_SimRenderFreq() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulationLoopFrequency_SimLoopFreq() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSimulationDuration_SimDuration() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_ArtificialPhenomenas() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Clouding() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Humidity() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_OpticalPhenomenas() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Precipitationamount() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Precipitationtype() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Pressure() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Sight() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Temperature() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_WeatherPhenomenas() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Winddirection() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeatherObj_Windstrength() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeather_FixedWeather() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeather_Forecast() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeather_RandomWeather() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTWeather_SequenceWeather() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTFixedWeather_FixedWeatherObj() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSequenceWeather_RandomWeatherObj() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTSequenceWeather_SequenceDuration() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTRandomWeather_RandomDuration() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTForecast_ForecastDuration() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTForecast_ForecastWeatherObj() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTTime_TimeHours() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTTime_TimeMilliseconds() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTTime_TimeMinutes() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTTime_TimeSeconds() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTTime_UnitNumber() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMapPath_MapPath() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMapName_MapName() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMapHeight_HeightMap() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMapOverlap_MapOverlap() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMapSectorWidth_SectorWidth() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMapSectorHeight_SectorHeight() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTMaxSectorUsers_MaxSectorUsers() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTTimeout_Timeout() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPedestrians_EndX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPedestrians_EndY() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPedestrians_EndZ() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPedestrians_StartX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPedestrians_StartY() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPedestrianDensity_PedestrianDensity() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTVehicles_ExplicitVehicles() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTVehicles_PathedVehicles() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTVehicles_RandomVehicles() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTExplicitVehicle_DestX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTExplicitVehicle_DestY() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTExplicitVehicle_DestZ() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTExplicitVehicle_StartRot() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTExplicitVehicle_StartX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTExplicitVehicle_StartY() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTExplicitVehicle_Vehicle() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTPathedVehicle_Amount() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPathedVehicle_DestRadius() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPathedVehicle_DestX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPathedVehicle_DestY() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPathedVehicle_SpawnRadius() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPathedVehicle_SpawnX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTPathedVehicle_SpawnY() ;

  /* generated by template ast.ClassMethod*/
  
   EAttribute getASTRandomVehicle_Amount() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTRandomVehicle_DestX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTRandomVehicle_DestY() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTRandomVehicle_StartX() ;

  /* generated by template ast.ClassMethod*/
  
   EReference getASTRandomVehicle_StartY() ;

     
  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
  */
  interface Literals {
  
    EEnum ConstantsSimulation = eINSTANCE.getConstantsSimulation();
    
    EClass ASTSimulation = eINSTANCE.getSimulation();
    EClass ASTSimulationRenderFrequency = eINSTANCE.getSimulationRenderFrequency();
    EClass ASTSimulationLoopFrequency = eINSTANCE.getSimulationLoopFrequency();
    EClass ASTSimulationDuration = eINSTANCE.getSimulationDuration();
    EClass ASTSimulationType = eINSTANCE.getSimulationType();
    EClass ASTWeatherObj = eINSTANCE.getWeatherObj();
    EClass ASTWeather = eINSTANCE.getWeather();
    EClass ASTFixedWeather = eINSTANCE.getFixedWeather();
    EClass ASTSequenceWeather = eINSTANCE.getSequenceWeather();
    EClass ASTRandomWeather = eINSTANCE.getRandomWeather();
    EClass ASTForecast = eINSTANCE.getForecast();
    EClass ASTTime = eINSTANCE.getTime();
    EClass ASTMapPath = eINSTANCE.getMapPath();
    EClass ASTMapName = eINSTANCE.getMapName();
    EClass ASTMapHeight = eINSTANCE.getMapHeight();
    EClass ASTMapOverlap = eINSTANCE.getMapOverlap();
    EClass ASTMapSectorWidth = eINSTANCE.getMapSectorWidth();
    EClass ASTMapSectorHeight = eINSTANCE.getMapSectorHeight();
    EClass ASTMaxSectorUsers = eINSTANCE.getMaxSectorUsers();
    EClass ASTTimeout = eINSTANCE.getTimeout();
    EClass ASTPedestrians = eINSTANCE.getPedestrians();
    EClass ASTPedestrianDensity = eINSTANCE.getPedestrianDensity();
    EClass ASTVehicles = eINSTANCE.getVehicles();
    EClass ASTExplicitVehicle = eINSTANCE.getExplicitVehicle();
    EClass ASTPathedVehicle = eINSTANCE.getPathedVehicle();
    EClass ASTRandomVehicle = eINSTANCE.getRandomVehicle();
  }
}

