/* generated by template cocos.CoCoInterface*/



package weather._cocos;

import weather._ast.ASTPrecipitationtype;

public interface WeatherASTPrecipitationtypeCoCo {
  public void check(ASTPrecipitationtype node);
}
