/* generated by template cocos.CoCoInterface*/



package weather._cocos;

import weather._ast.ASTWeatherNode;

public interface WeatherASTWeatherNodeCoCo {
  public void check(ASTWeatherNode node);
}
