#
# (c) https://github.com/MontiCore/monticore
#
# The license generally applicable for this project
# can be found under https://github.com/MontiCore/monticore.
#

# (c) https://github.com/MontiCore/monticore
#
#image: maven:3-jdk-8
#
#
#masterJob:
#  script:
#  - "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install deploy --settings settings.xml"
#  - cat target/site/jacoco/index.html
#  only:
#  - master
#
#BranchJob:
#  script:
#  - "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml"
#  - cat target/site/jacoco/index.html
#  except:
#  - master

stages:
- linux
#- windows
masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
#  image: atlassian/default-image:1
  script:
#  - gcc --help
  - mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
  - cat target/site/jacoco/index.html
  only:
  - master
  except:
    changes:
    - .gitlab-ci.yml
    - README.md
    - .gitignore
#
#masterJobWindows:
#  stage: windows
#  script:
#  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
#  tags:
#  - Windows10_OS
#
BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script:
  - mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  - cat target/site/jacoco/index.html
  except:
  - master
#
#BranchJobWindows:
#  stage: windows
#  script:
#  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
#  tags:
#  - Windows10_OS
