/**
 *
 * (c) https://github.com/MontiCore/monticore
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/* (c) https://github.com/MontiCore/monticore */
/* generated by template symboltable.Symbol*/


package de.monticore.lang.monticar.cnnarch._symboltable;

import de.monticore.symboltable.Scope;
import de.monticore.symboltable.Symbol;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class IODeclarationSymbol extends VariableDeclarationSymbol {

    public static final Integer MAX_ARRAY_LENGTH = 10000;

    private ArchTypeSymbol type;
    private boolean input; //true->input, false->output
    private int arrayLength = 1;
    private ArchitectureSymbol architecture = null; // set by ArchitectureSymbol

    protected IODeclarationSymbol(String name) {
        super(name);
    }

    public ArchTypeSymbol getType() {
        return type;
    }

    protected void setType(ArchTypeSymbol type) {
        this.type = type;
    }

    public List<VariableSymbol> getConnectedElements() {
        if (getArchitecture() == null){
            return new ArrayList<>();
        }
        else {
            List<VariableSymbol> completeList;
            if (input) {
                completeList = getArchitecture().getInputs();
            } else {
                completeList = getArchitecture().getOutputs();
            }
            return completeList.stream()
                    .filter(e -> e.getName().equals(getName()))
                    .collect(Collectors.toList());
        }
    }

    public boolean isOutput(){
        return !input;
    }

    public boolean isInput() {
        return input;
    }

    protected void setInput(boolean input) {
        this.input = input;
    }

    public int getArrayLength() {
        return arrayLength;
    }

    protected void setArrayLength(int arrayLength) {
        this.arrayLength = arrayLength;
    }

    public ArchitectureSymbol getArchitecture() {
        return (ArchitectureSymbol) getEnclosingScope().resolve("", ArchitectureSymbol.KIND).get();
    }

    @Override
    public void putInScope(Scope scope){
        Collection<Symbol> symbolsInScope = scope.getLocalSymbols().get(getName());
        if (symbolsInScope == null || !symbolsInScope.contains(this)) {
            scope.getAsMutableScope().add(this);
            getType().putInScope(scope);
        }
    }

    @Override
    public VariableDeclarationSymbol preResolveDeepCopy(){
        IODeclarationSymbol copy = new IODeclarationSymbol(getName());
        if (getAstNode().isPresent()){
            copy.setAstNode(getAstNode().get());
        }

        copy.setInput(isInput());
        copy.setArrayLength(getArrayLength());
        copy.setType(getType().preResolveDeepCopy());

        return copy;
    }

    public static class Builder{
        private ArchTypeSymbol type;
        private boolean input; //true->input, false->output
        private int arrayLength = 0;
        private String name;

        public Builder type(ArchTypeSymbol type){
            this.type = type;
            return this;
        }

        public Builder input(boolean input){
            this.input = input;
            return this;
        }

        public Builder arrayLength(int arrayLength){
            this.arrayLength = arrayLength;
            return this;
        }

        public Builder name(String name){
            this.name = name;
            return this;
        }

        public IODeclarationSymbol build(){
            if (name == null || name.equals("")){
                throw new IllegalStateException("Missing or empty name for IO declaration");
            }
            IODeclarationSymbol sym = new IODeclarationSymbol(name);
            sym.setInput(input);
            sym.setArrayLength(arrayLength);
            sym.setType(type);
            return sym;
        }
    }
}
