/**
 *
 * (c) https://github.com/MontiCore/monticore
 *
 * The license generally applicable for this project
 * can be found under https://github.com/MontiCore/monticore.
 */
/* (c) https://github.com/MontiCore/monticore */
/* generated by template symboltable.ScopeSpanningSymbol*/


package de.monticore.lang.monticar.cnnarch._symboltable;

import de.monticore.lang.monticar.cnnarch.predefined.AllPredefinedVariables;
import de.monticore.symboltable.CommonScopeSpanningSymbol;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class LayerDeclarationSymbol extends CommonScopeSpanningSymbol {

    public static final LayerDeclarationKind KIND = new LayerDeclarationKind();

    private List<ParameterSymbol> parameters;
    private SerialCompositeElementSymbol body;


    protected LayerDeclarationSymbol(String name) {
        super(name, KIND);
    }

    @Override
    protected LayerDeclarationScope createSpannedScope() {
        return new LayerDeclarationScope();
    }

    @Override
    public LayerDeclarationScope getSpannedScope() {
        return (LayerDeclarationScope) super.getSpannedScope();
    }

    public List<ParameterSymbol> getParameters() {
        return parameters;
    }

    protected void setParameters(List<ParameterSymbol> parameters) {
        this.parameters = parameters;
        if (!getParameter(AllPredefinedVariables.CONDITIONAL_ARG_NAME).isPresent()){
            ParameterSymbol ifParam = AllPredefinedVariables.createConditionalParameter();
            this.parameters.add(ifParam);
            ifParam.putInScope(getSpannedScope());
        }
        if (!getParameter(AllPredefinedVariables.SERIAL_ARG_NAME).isPresent()){
            ParameterSymbol forParam = AllPredefinedVariables.createSerialParameter();
            this.parameters.add(forParam);
            forParam.putInScope(getSpannedScope());
        }
        if (!getParameter(AllPredefinedVariables.PARALLEL_ARG_NAME).isPresent()){
            ParameterSymbol forParam = AllPredefinedVariables.createParallelParameter();
            this.parameters.add(forParam);
            forParam.putInScope(getSpannedScope());
        }
    }

    public SerialCompositeElementSymbol getBody() {
        return body;
    }

    protected void setBody(SerialCompositeElementSymbol body) {
        this.body = body;
    }

    public boolean isPredefined() {
        //Override by PredefinedLayerDeclaration
        return false;
    }

    public boolean isCustom(){
        return false;
    }

    public Optional<ParameterSymbol> getParameter(String name) {
        Optional<ParameterSymbol> res = Optional.empty();
        for (ParameterSymbol parameter : getParameters()){
            if (parameter.getName().equals(name)){
                res = Optional.of(parameter);
            }
        }
        return res;
    }


    public ArchitectureElementSymbol call(LayerSymbol layer) throws ArchResolveException{
        checkForSequence(layer.getArguments());

        if (isPredefined() || isCustom()){
            return layer;
        }
        else {
            reset();
            set(layer.getArguments());

            SerialCompositeElementSymbol copy = getBody().preResolveDeepCopy();
            copy.putInScope(getSpannedScope());
            copy.resolveOrError();
            getSpannedScope().remove(copy);
            getSpannedScope().removeSubScope(copy.getSpannedScope());

            reset();
            return copy;
        }
    }

    private void reset(){
        for (ParameterSymbol param : getParameters()){
            param.reset();
        }
    }

    private void set(List<ArgumentSymbol> arguments){
        for (ArgumentSymbol arg : arguments){
            arg.set();
        }
    }

    private void checkForSequence(List<ArgumentSymbol> arguments){
        boolean valid = true;
        for (ArgumentSymbol arg : arguments){
            if (arg.getRhs() instanceof  ArchAbstractSequenceExpression){
                valid = false;
            }
        }
        if (!valid){
            throw new IllegalArgumentException("Arguments with sequence expressions have to be resolved first before calling the layer method.");
        }
    }

    public LayerDeclarationSymbol deepCopy() {
        LayerDeclarationSymbol copy = new LayerDeclarationSymbol(getName());
        if (getAstNode().isPresent()){
            copy.setAstNode(getAstNode().get());
        }

        List<ParameterSymbol> parameterCopies = new ArrayList<>(getParameters().size());
        for (ParameterSymbol parameter : getParameters()){
            ParameterSymbol parameterCopy = parameter.deepCopy();
            parameterCopies.add(parameterCopy);
            parameterCopy.putInScope(copy.getSpannedScope());
        }
        copy.setParameters(parameterCopies);
        copy.setBody(getBody().preResolveDeepCopy());
        copy.getBody().putInScope(copy.getSpannedScope());
        return copy;
    }


    /*public static class Builder{
        private List<ParameterSymbol> parameters = new ArrayList<>();
        private CompositeElementSymbol body;
        private String name = "";

        public Builder parameters(List<ParameterSymbol> parameters) {
            this.parameters = parameters;
            return this;
        }

        public Builder parameters(ParameterSymbol... parameters) {
            this.parameters = new ArrayList<>(Arrays.asList(parameters));
            return this;
        }

        public Builder body(CompositeElementSymbol body) {
            this.body = body;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public LayerDeclarationSymbol build(){
            if (name == null || name.equals("")){
                throw new IllegalStateException("Missing or empty name for LayerDeclarationSymbol");
            }
            LayerDeclarationSymbol sym = new LayerDeclarationSymbol(name);
            sym.setBody(body);
            if (body != null){
                body.putInScope(sym.getSpannedScope());
            }
            for (ParameterSymbol param : parameters){
                param.putInScope(sym.getSpannedScope());
            }
            sym.setParameters(parameters);
            return sym;
        }
    }*/
}
