/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.PowerConsumptionTagSchema;

import de.monticore.CommonModelingLanguage;
import de.monticore.lang.tagging._symboltable.TagableModelingLanguage;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class PowerConsumptionTagSchema {

  protected static PowerConsumptionTagSchema instance = null;

  protected PowerConsumptionTagSchema() {}

  protected static PowerConsumptionTagSchema getInstance() {
    if (instance == null) {
      instance = new PowerConsumptionTagSchema();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TagableModelingLanguage modelingLanguage) {
    // all ModelingLanguage instances are actually instances of CommonModelingLanguage
    if(modelingLanguage instanceof CommonModelingLanguage) {
      CommonModelingLanguage commonModelingLanguage = (CommonModelingLanguage)modelingLanguage;

      modelingLanguage.addTagSymbolCreator(new PowerConsumptionSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(PowerConsumptionSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new PowerTesterSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(PowerTesterSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new PowerIdSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(PowerIdSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new PowerBooleanSymbolCreator());
      commonModelingLanguage.addResolvingFilter(CommonResolvingFilter.create(PowerBooleanSymbol.KIND));
    }
  }

  public static void registerTagTypes(TagableModelingLanguage modelingLanguage) {
    getInstance().doRegisterTagTypes(modelingLanguage);
  }
}