<#-- (c) https://github.com/MontiCore/monticore -->
# generated by ros.MsgGen.CMakeLists.ftl
cmake_minimum_required(VERSION 2.8.12)
project(struct_msgs)
find_package(genmsg REQUIRED)

<#list viewModel.getFileNamesOnly() as fileOnly>
add_message_files(FILES ${fileOnly})
</#list>
<#noparse>
set(CATKIN_MESSAGE_GENERATORS gencpp)
generate_messages()
set(struct_msgs_INCLUDE_DIRS ${struct_msgs_INCLUDE_DIRS} PARENT_SCOPE)
</#noparse>
