# (c) https://github.com/MontiCore/monticore
#
stages:
- linux

masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script: 
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "master" 
      changes:
        - src/**/*
        - pom.xml
        - settings.xml


BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script: 
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  except:
  - master
