# In order to update the 'shared_cpp' submodule
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - linux
  #- windows

githubjob:
  image: maven:3-jdk-8
  stage: linux
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITHUB_SSH_PRIV_KEY")
  - echo "$GITHUB_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "EMA CI Robot"
  - mkdir -p ~/.ssh
#  - cat gitlab-known-hosts >> ~/.ssh/known_hosts
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script: 
  - git clone git@github.com:MontiCore/EmbeddedMontiArc.git
  - cd EmbeddedMontiArc
  - git subtree pull --prefix $PRJ_NAME https://git.rwth-aachen.de/monticore/EmbeddedMontiArc/${PRJ_NAME}.git master --squash
  - git push --force
  only:
  - master

masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script:
    - apt-get update -q && apt-get install -y -q g++ libhdf5-serial-dev libhdf5-dev libopenblas-dev
    - gcc --help
    - mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
    - cat target/site/jacoco/index.html
#    - mvn package sonar:sonar -s settings.xml
  only:
    - master
  except:
    changes:
    - README.md
    - .gitignore
    - .gitlab-ci.yml


#masterJobWindows:
#  stage: windows
#  script:
#  - mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml -U
#  only:
#    - master
#  tags:
#  - Windows10

BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script:
    - apt-get update -q && apt-get install -y -q g++ libhdf5-serial-dev libhdf5-dev libopenblas-dev
    - mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
    - cat target/site/jacoco/index.html
  except:
    - master


#BranchJobWindows:
#  stage: windows
#  script:
#  - mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml -U
#  - cat target/site/jacoco/index.html
#  except:
#  - master
#  tags:
#  - Windows10
