/* (c) https://github.com/MontiCore/monticore */
/* generated from model null*/
/* generated by template symboltable.ModelingLanguage*/


package de.monticore.lang.monticar.stream._symboltable;

public class StreamLanguage extends StreamLanguageTOP {

    public static final String FILE_ENDING = "stream";

    public StreamLanguage() {
        super("Stream Language", FILE_ENDING);
        setModelNameCalculator(new StreamModelNameCalculator());
    }

    @Override
    protected StreamModelLoader provideModelLoader() {
        return new StreamModelLoader(this);
    }

}
