PROJECT_ROOT="$(pwd)"
BINARY="target/bin"
GENERATOR_PATH="bin/embedded-montiarc-math-middleware-generator-0.1.4-SNAPSHOT-jar-with-dependencies.jar"
AGENT_BUILD="target/agent/build"
SIMULATOR_PATH="$HOME/dev/basic-simulator/install"
SCENARIO_PATH="scenarios/rl_autopilot_160.json"
DIR_NAME="Autopilot2"
SAVE_FOLDER="$HOME/dev/coopmontisimautopilot/saved_autopilots"
