/* generated by template cocos.CoCoInterface*/



package weather._cocos;

import weather._ast.ASTArtificialPhenomena;

public interface WeatherASTArtificialPhenomenaCoCo {
  public void check(ASTArtificialPhenomena node);
}
