/* generated by template cocos.CoCoInterface*/



package weather._cocos;

import weather._ast.ASTTemperature;

public interface WeatherASTTemperatureCoCo {
  public void check(ASTTemperature node);
}
