/* generated by template cocos.CoCoInterface*/



package weather._cocos;

import weather._ast.ASTWeatherPhenomena;

public interface WeatherASTWeatherPhenomenaCoCo {
  public void check(ASTWeatherPhenomena node);
}
