/* (c) https://github.com/MontiCore/monticore */
/* generated from model null*/
/* generated by template templates.de.monticore.lang.tagschema.SimpleTagType*/


package drawing.TraceabilityTagSchema;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;

/**
 * Created by SimpleTagType.ftl
 */
public class IsTraceableSymbol extends TagSymbol {
  public static final IsTraceableKind KIND = IsTraceableKind.INSTANCE;

  /**
   * is marker symbol so it has no value by itself
   */
  public IsTraceableSymbol() {
    super(KIND);
  }

  protected IsTraceableSymbol(IsTraceableKind kind) {
    super(kind);
  }

  @Override
  public String toString() {
    return "IsTraceable";
  }

  public static class IsTraceableKind extends TagKind {
    public static final IsTraceableKind INSTANCE = new IsTraceableKind();

    protected IsTraceableKind() {
    }
  }
}
