/* (c) https://github.com/MontiCore/monticore */
package de.monticore.lang.embeddedmontiarc.embeddedmontiarcapplication._ast;

import de.monticore.lang.embeddedmontiarc.embeddedmontiarc._ast.ASTComponentBody;
import de.monticore.lang.embeddedmontiarc.embeddedmontiarcapplication._visitor.EmbeddedMontiArcApplicationVisitor;
import de.monticore.lang.monticar.common2._ast.ASTParameter;
import de.monticore.lang.monticar.types2._ast.ASTTypeParameters2;
import de.monticore.types.types._ast.ASTReferenceType;

import java.util.List;
import java.util.Optional;

/**
 */
public class ASTComponent extends ASTComponentTOP {
    public ASTComponent() {
    }

    public ASTComponent(String name, Optional<ASTTypeParameters2> genericTypeParameters, List<ASTParameter> parameters, Optional<ASTReferenceType> superComponent, ASTComponentBody body) {
        super(name, genericTypeParameters, parameters, superComponent, body);
    }

    @Override
    public void accept(EmbeddedMontiArcApplicationVisitor visitor)   {
        /* generated by template ast.ErrorIfNull*/
        // MontiCore generally assumes that null is not used, but if you are
        // unsure then override template ast.ErrorIfNull
        // Log.errorIfNull(visitor, "0xA7006x255 Parameter 'visitor' must not be null.");

        /* generated by template ast.additionalmethods.Accept*/

        // We allow a down cast here, because the subclass ASTComponent must exist
        // and only this subclass may exist in the AST and hence, only this class may
        // be handled by a visitor. All other cases are invalid an throw an exception!
        // This decision was made during MC Sprint Review on 16.03.2015.
        if (this instanceof de.monticore.lang.embeddedmontiarc.embeddedmontiarc._ast.ASTComponent) {
            visitor.handle((de.monticore.lang.embeddedmontiarc.embeddedmontiarc._ast.ASTComponent) this);
        } else {
            throw new UnsupportedOperationException("0xA7010x664 Only handwritten class ASTComponent is supported for the visitor");
        }

    }

    @Override
    public void accept(de.monticore.lang.embeddedmontiarc.embeddedmontiarc._visitor.EmbeddedMontiArcVisitor visitor) {
        /* generated by template ast.ErrorIfNull*/
        // MontiCore generally assumes that null is not used, but if you are
        // unsure then override template ast.ErrorIfNull
        // Log.errorIfNull(visitor, "0xA7006x255 Parameter 'visitor' must not be null.");

        /* generated by template ast.additionalmethods.Accept*/

        // We allow a down cast here, because the subclass ASTComponent must exist
        // and only this subclass may exist in the AST and hence, only this class may
        // be handled by a visitor. All other cases are invalid an throw an exception!
        // This decision was made during MC Sprint Review on 16.03.2015.
        if (this instanceof de.monticore.lang.embeddedmontiarc.embeddedmontiarc._ast.ASTComponent) {
            visitor.handle((de.monticore.lang.embeddedmontiarc.embeddedmontiarc._ast.ASTComponent) this);
        } else {
            throw new UnsupportedOperationException("0xA7010x664 Only handwritten class ASTComponent is supported for the visitor");
        }

    }
}
