/* generated from model Weather*/
/* generated by template ast.AstClass*/

package weather._ast;

/* generated by template ast_emf.AstEImports*/
import java.util.Optional;
import java.util.Iterator;
import de.se_rwth.commons.logging.Log;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;

 public  class ASTSight extends /* generated by template ast.AstSuperTypes*/
de.monticore.emf._ast.ASTECNode implements  ASTWeatherNode
 {
  /* generated by template ast.Attribute*/
  
   protected  Optional<si._ast.ASTUnitNumber> weatherSight = Optional.empty();

    /* generated by template ast.Constructor*/
  
   protected  ASTSight (/* generated by template ast.ParametersDeclaration*/
    // Parameters declaration
 
    )  
  /* generated by template ast.EmptyMethodBody*/

  { // empty body 
  }


    /* generated by template ast.Constructor*/
  
   protected  ASTSight (/* generated by template ast.ConstructorParametersDeclaration*/
     si._ast.ASTUnitNumber weatherSight 
 
    )  
  /* generated by template ast.ConstructorAttributesSetter*/
  {
    setWeatherSight(weatherSight);
  }


  
    /* generated by template ast.ClassMethod*/
  
   public  void accept(weather._visitor.WeatherVisitor visitor)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(visitor, "0xA7006_918 Parameter 'visitor' must not be null.");

     /* generated by template ast.additionalmethods.Accept*/

      visitor.handle(this);

  } 

    /* generated by template ast.ClassMethod*/
  
   public  void accept(si._visitor.SIVisitor visitor)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(visitor, "0xA7006_930 Parameter 'visitor' must not be null.");

     /* generated by template ast.additionalmethods.AcceptSuper*/

    if (visitor instanceof weather._visitor.WeatherVisitor) {
      accept((weather._visitor.WeatherVisitor) visitor);      
    } else {
      de.se_rwth.commons.logging.Log.error("0xA7000_209AST node type ASTSight of the sub language Weather expected a visitor of type weather._visitor.WeatherVisitor, but got si._visitor.SIVisitor. Visitors of a super language may not be used on ASTs containing nodes of the sub language. Use a visitor of the sub language.");
    }

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEquals(Object o,boolean forceSameOrder)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_139 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.DeepEqualsWithOrder*/

      ASTSight comp;
    if ((o instanceof ASTSight)) {
      comp = (ASTSight) o;
    } else {
      return false;
    }
    if (!equalAttributes(comp)) {
      return false;
    }
    // comparing weatherSight   
    if ( this.weatherSight.isPresent() != comp.weatherSight.isPresent() ||
      (this.weatherSight.isPresent() && !this.weatherSight.get().deepEquals(comp.weatherSight.get())) ) {
      return false;
    }
    return true;     


  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEquals(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_923 Parameter 'o' must not be null.");

     return deepEquals(o, true);

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEqualsWithComments(Object o,boolean forceSameOrder)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_185 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.DeepEqualsWithComments*/

      ASTSight comp;
    if ((o instanceof ASTSight)) {
      comp = (ASTSight) o;
    } else {
      return false;
    }
    if (!equalsWithComments(comp)) {
      return false;
    }
    // comparing weatherSight
    if ( this.weatherSight.isPresent() != comp.weatherSight.isPresent() ||
      (this.weatherSight.isPresent() && !this.weatherSight.get().deepEqualsWithComments(comp.weatherSight.get())) ) {
      return false;
    }
    return true;     

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean deepEqualsWithComments(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_995 Parameter 'o' must not be null.");

     return deepEqualsWithComments(o, true);

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean equalAttributes(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_125 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.EqualAttributes*/

      ASTSight comp;
    if ((o instanceof ASTSight)) {
      comp = (ASTSight) o;
    } else {
      return false;
    }
    return true;     


  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean equalsWithComments(Object o)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(o, "0xA7006_195 Parameter 'o' must not be null.");

     /* generated by template ast.additionalmethods.EqualsWithComments*/

      ASTSight comp;
    if ((o instanceof ASTSight)) {
      comp = (ASTSight) o;
    } else {
      return false;
    }
    if (!equalAttributes(comp)) {
      return false;
    }
    // comparing comments
    if (get_PreComments().size() == comp.get_PreComments().size()) {
      java.util.Iterator<de.monticore.ast.Comment> one = get_PreComments().iterator();
      java.util.Iterator<de.monticore.ast.Comment> two = comp.get_PreComments().iterator();
      while (one.hasNext()) {
        if (!one.next().equals(two.next())) {
          return false;
        }
      }
    } else {
      return false;
    }
    
    if (get_PostComments().size() == comp.get_PostComments().size()) {
      java.util.Iterator<de.monticore.ast.Comment> one = get_PostComments().iterator();
      java.util.Iterator<de.monticore.ast.Comment> two = comp.get_PostComments().iterator();
      while (one.hasNext()) {
        if (!one.next().equals(two.next())) {
          return false;
        }
      }
    } else {
      return false;
    }
    return true;

  } 

    /* generated by template ast.ClassMethod*/
  
   public  java.util.Collection<de.monticore.ast.ASTNode> get_Children()   { 
     
     /* generated by template ast.additionalmethods.GetChildren*/

    java.util.LinkedList<de.monticore.ast.ASTNode> result = new java.util.LinkedList<de.monticore.ast.ASTNode>();
        if (getWeatherSight().isPresent()) {
          result.add(getWeatherSight().get());
        }
    return result;

  } 

    /* generated by template ast.ClassMethod*/
  
   public  void remove_Child(de.monticore.ast.ASTNode child)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(child, "0xA7006_310 Parameter 'child' must not be null.");

     /* generated by template ast.additionalmethods.RemoveChild*/

      if (getWeatherSight().isPresent() && getWeatherSight().get() == child) {
        setWeatherSight(null);
      }

  } 

    /* generated by template ast.ClassMethod*/
  
   public  static  Builder getBuilder()   { 
     
     return new Builder();

  } 

    /* generated by template ast.ClassMethod*/
  
   public  ASTSight deepClone()   { 
     
     return deepClone(_construct());

  } 

    /* generated by template ast.ClassMethod*/
  
   public  ASTSight deepClone(ASTSight result)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(result, "0xA7006_071 Parameter 'result' must not be null.");

     /* generated by template ast.additionalmethods.DeepCloneWithParameters*/
  
    super.deepClone(result);
    
    result.weatherSight = this.weatherSight.isPresent()? Optional.ofNullable((si._ast.ASTUnitNumber)this.weatherSight.get().deepClone()) : Optional.empty();
    
    return result;

  } 

    /* generated by template ast.ClassMethod*/
  
   protected  ASTSight _construct()   { 
     
     return new ASTSight();

  } 

    /* generated by template ast.ClassMethod*/
  
   public  Optional<si._ast.ASTUnitNumber> getWeatherSight()   { 
     
     /* generated by template ast.additionalmethods.Get*/

    return  this.weatherSight;

  } 

    /* generated by template ast.ClassMethod*/
  
   public  void setWeatherSight(si._ast.ASTUnitNumber weatherSight)   { 
     
     /* generated by template ast_emf.additionalmethods.Set*/

    si._ast.ASTUnitNumber oldWeatherSight = this.weatherSight.isPresent()? this.weatherSight.get() : null;
    this.weatherSight = Optional.ofNullable(weatherSight);
    if (eNotificationRequired()) {
      eNotify(new ENotificationImpl(this, Notification.SET, WeatherPackage.ASTSight_WeatherSight, oldWeatherSight, weatherSight));
    }  

  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean weatherSightIsPresent()   { 
     
       return weatherSight.isPresent(); 

  } 

    /* generated by template ast.ClassMethod*/
  
   public  Object eGet(int featureID,boolean resolve,boolean coreType)   { 
     
     /* generated by template ast_emf.additionalmethods.EGet*/
  
    switch (featureID) {
      case WeatherPackage.ASTSight_WeatherSight:
         return getWeatherSight().isPresent()? getWeatherSight().get() : null;
    }
    return eDynamicGet(featureID, resolve, coreType);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  void eSet(int featureID,Object newValue)   { 
     
     /* generated by template ast_emf.additionalmethods.ESet*/
  
    switch (featureID) {
      case WeatherPackage.ASTSight_WeatherSight:
        setWeatherSight((si._ast.ASTUnitNumber)newValue);
        return;
    }
    eDynamicSet(featureID, newValue);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  void eUnset(int featureID)   { 
     
     /* generated by template ast_emf.additionalmethods.EUnset*/
 
    switch (featureID) {
      case WeatherPackage.ASTSight_WeatherSight:
        setWeatherSight(null);
      return;
    }
    eDynamicUnset(featureID);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  boolean eIsSet(int featureID)   { 
     
     /* generated by template ast_emf.additionalmethods.EIsSet*/
 
    switch (featureID) {
      case WeatherPackage.ASTSight_WeatherSight:
        return getWeatherSight().isPresent();
    }
    return eDynamicIsSet(featureID);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  int eBaseStructuralFeatureID(int featureID,Class<?> baseClass)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(baseClass, "0xA7006_839 Parameter 'baseClass' must not be null.");

     /* generated by template ast_emf.additionalmethods.EStructuralFeature*/
  
    return super.eBaseStructuralFeatureID(featureID, baseClass);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  int eDerivedStructuralFeatureID(int featureID,Class<?> baseClass)   { 
     /* generated by template ast.ErrorIfNull*/
    Log.errorIfNull(baseClass, "0xA7006_534 Parameter 'baseClass' must not be null.");

     /* generated by template ast_emf.additionalmethods.EStructuralFeature*/
  
    return super.eDerivedStructuralFeatureID(featureID, baseClass);
  } 

    /* generated by template ast.ClassMethod*/
  
   public  String toString()   { 
     
     /* generated by template ast_emf.additionalmethods.EToString*/
  
    if (eIsProxy()) {
      return super.toString();
    }
    StringBuffer result = new StringBuffer(getClass().getSimpleName());
    if (weatherSight.isPresent()) {
      result.append(" WeatherSight: ");
      result.append(weatherSight.get());
    } 
    return result.toString();
  } 

    /* generated by template ast.ClassMethod*/
  
   protected  EClass eStaticClass()   { 
     
     return WeatherPackage.Literals.ASTSight;
  } 

   
  /* generated by template ast.ClassContent*/
  // Class content

    /* generated by template ast.AstBuilder*/

 /**
   * Builder for {@link ASTSight}.
   */
  public static class Builder  {
    /* generated by template ast.BuilderAttribute*/
     protected  si._ast.ASTUnitNumber weatherSight;

    public ASTSight build() {
      return new ASTSight (/* generated by template ast.BuilderConstructorParametersDeclaration*/
  
        this.weatherSight 

      );
    }
    /* generated by template ast.AstBuilderAttributeSetter*/
    public Builder weatherSight(si._ast.ASTUnitNumber weatherSight) {
      this.weatherSight = weatherSight;
      return this;
    }

  }    

  
}
