/* generated from model Weather*/
/* generated by template ast.AstEnum*/

package weather._ast;



public enum WeatherLiterals implements org.eclipse.emf.common.util.Enumerator {
      DEFAULT(ASTConstantsWeather.DEFAULT) 
  ;
 
  protected int intValue;
  
  private WeatherLiterals(int intValue){
    this.intValue=intValue;
  }
  
  public int intValue() {
    return intValue;
  }
  
  /* generated by template ast.ClassMethod*/
  
   public  String getName()   { 
     
       return toString(); 

  } 

  /* generated by template ast.ClassMethod*/
  
   public  String getLiteral()   { 
     
       return toString(); 

  } 

  /* generated by template ast.ClassMethod*/
  
   public  int getValue()   { 
     
       return intValue; 

  } 

}
