productName: EmbeddedMontiArcStudio
appId: se.rwth.emastudio

asar: false
directories:
  buildResources: build
  output: dist
files:
  - "src/electron/**/*"
  - "node_modules/**/*"
  - "package.json"
extraResources:
  - from: "src/models"
    to: "models"
  - from: "src/cluster-fiddle"
    to: "cluster-fiddle"
  - from: "src/oclverification"
    to: "oclverification"
extraFiles:
  - from: "cache/resources/app/lib/vs"
    to: "vs"
    filter:
      - "**/*.js"
      - "!**/loader.js"
afterPack: "scripts/afterPack.js"

win:
  icon: build/icon.ico
  extraResources:
    - from: "src/windows/scripts"
      to: "scripts"
  target:
    - "nsis"

linux:
  icon: build/icons
  category: Development
  extraResources:
    - from: "src/linux/scripts"
      to: "scripts"
  target:
    - "deb"

nsis:
  menuCategory: true
  oneClick: false
  perMachine: true
  installerHeaderIcon: build/icon.ico
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  installerSidebar: build/installerSidebar.bmp
  uninstallerSidebar: build/installerSidebar.bmp
  allowToChangeInstallationDirectory: true
  runAfterFinish: false
  artifactName: ${productName}-Installer-${version}.${ext}

deb:
  artifactName: ${productName}-Installer-${version}.${ext}
# depends: Can be used to add Linux package dependencies such as "build-essentials" or similar.
#   - "Package-1"
#   - "Package-2"