# (c) https://github.com/MontiCore/monticore

stages:
- linux

TestLifeongLanguageLearningTraining:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
  - cd lifelong-language-learning
  - mvn streamtest:streamtest-build -s settings.xml

TestLifeongLanguageLearningPrediction:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
  script:
  - cd gluon
  - chmod +x build.sh
  - ./build.sh
  - RES=$(./build/src/cpp/LifelongLanguageLearning resources/prediction_data/prediction_samples.txt resources/prediction_data/prediction_sequences.txt resources/prediction_data/prediction_lengths.txt)
  - "if [[ $RES != *\"Prediction for sample 0: 0\"* ]]; then echo \"Wrong result:\" $RES; exit 1; fi;"
  