console.log(
`MMMMWNXXXXXXXXXXXXXXXXXXNWMMWXXXNWMMMMMMMMMMMMMMMNXXXNMMMMMMMMMMMMMWNXXXWMMMMMMWNXXXXXXXXXXXXXXXNMMMMMNXXXNMMMWXXXNWMMMMMMMMMMMMMNXXXNMMMMWX0XWMMMMMMMMMMMMMMMMMMN0KWMMMM
MMMX:                   ;KMMO.  .OMMMMMMMMMMMMMMWl   lWMMMMMMMMMMMMK,  .kMM0:                   cNMMMNc   oWMMk.  '0MMMMMMMMMMMMWl   cNMMN:   .oNMMMMMMMMMMMMMNd.   ,KMMM
MMMX:   c000000000000000XWMMO.  .OMMMMMMMMMMMMMMNl   lWMMMMMMMMMMMMK,  .kMX:   ,x000000000000000XWMMMNc   oWMMk.  '0MMMMMMMMMMMMWl   cNMMN:     lXMMMMMMMMMMMNo.    ,KMMM
MMMX:  .dWMMMMMMMMMMMMMMMMMMO.  .OMMMMMMMMMMMMMMNl   lWMMMMMMMMMMMM0,  .kMK,  .xWMMMMMMMMMMMMMMMMMMMMNc   lWMMk.  '0MMMMMMMMMMMMWl   cNMMN:      :KMMMMMMMMMXc      ,KMMM
MMMX:  .dN0xxxxxxxxxxxONMMMMO.  .OMMMMMMMMMMMMMMWo   ,KMMMMMMMMMMMWx.  .OMNc   'lxxxxxxxxxxxxOKNMMMMMNc   lWMMk.  '0MMMMMMMMMMMMWl   cNMMN:       ;0WMMMMMMK:       ,KMMM
MMMX:  .d0,           'OMMMMO.  .OMMMMMMMMMMMMMMMK,   .coddddddddl;.   lNMMXl.                .'oKWMMNc   oWMMk.  '0MMMMMMMMMMMMWl   cNMMN:   :c   'OWMMMW0,   :c.  ,KMMM
MMMX:  .dKl,,,,,,,,,,,cKMMMMO.  .OMMMMMMMMMMMMMMMMKl.                ,xNMMMMW0dc;,,,,,,,,,,,'.   'OMMNc   oWMMO.  .OMMMMMMMMMMMMWl   cNMMN:   oXo.  .xWMWO'   lXx.  ,KMMM
MMMX:  .dWWWWWWWWWWWWWWMMMMMO.  .OMMMMMMMMMMMMMMMMMWKklc:;.   .,;:coONMMMMMMMMMMWWWWWWWWWWWWNK:   :NMNc   oWMMX:   :KMMMMMMMMMMMWl   cNMMN:   oWNd.  .dXx.  .oNMx.  ,KMMM
MMMX:   oWMMMMMMMMMMMMMMMMMMO.  .OMMMMMMMMMMMMMMMMMMMMMMMWx.  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc   :XMNc   oWMMM0,   'd0NWMMMMMMMWl   cNMMN:   oWMWk.  .'.  .dNMMx.  ,KMMM
MMMWo.  .;ccccccccccccccdXMMO.   ,cccccccccccccccxNMMMMMMMx.  ,KMMMMMMMMMMNkcccccccccccccccc:'   .xWMNc   oWMMMMKc.   .';:cccccc:.   cNMMN:   oWMMWO'     .xWMMMx.  ,KMMM
MMMMNd'                 '0MM0,                   ,KMMMMMMMx.  ,KMMMMMMMMMMX;                   .:OWMMNc   lWMMMMMW0o;.               oWMMN:   oWMMMM0;   'OWMMMMx.  ,KMMM
MMMMMMXOdoooooooooooooooxNMMW0dooooooooooooooooookNMMMMMMMKdookNMMMMMMMMMMWOooooooooooooooooodkKWMMMMWOooo0WMMMMMMMMWXOxooooooooooookXMMMWOooo0WMMMMMXdcoKWMMMMMKdookNMMM`
);
