console.log(
`MMMMMWWNNNNNNNNNNNWMMMWNNNNNNNNNNNNNNWMMMMMWWNWMMMMMMMMMWNNNNNNNNNNNNNWMMMMMWNNWMMMMMMMMMWWNNNNNNNNWMMMWNNWMMMMMWNNMMMMMWNNWMMM
MMO               kWNc   WMMMMMMMMMMk   0MMMMMMMMMk   0Wx               dNMMx   KM0   OMMMMMMMMM0   kMMx    KMMMMMMMMMNo   cNMM
MMO   kWWWWWWWWWWWWMNc   WMMMMMMMMMMk   0MMMMMMMMMk   0K   oNWWWWWWWWWWWWMMMx   KM0   OMMMMMMMMM0   OMMx     0WMMMMMMXc    cNMM
MMO   k0xxxxxxxxONMMNc   WMMMMMMMMMMO   xWMMMMMMMWo   KX    dxxxxxxxxkOXWMMMx   KM0   OMMMMMMMMM0   OMMx      OWMMMMK      cNMM
MMO   x          OMMNc   WMMMMMMMMMMNo    ccccccc    xWMKl              c0WMx   KM0   OMMMMMMMMM0   OMMx   c   xWMW0       cNMM
MMO   k0ddddddddkNMMNc   WMMMMMMMMMMMWOc           l0WMMMWXOxddddddddd    0Mx   KMX   oNMMMMMMMM0   OMMx   Kk   dNO   oXo  cNMM
MMO   kWWWWWWWWWWWMMNc   NWWWWWWWWWWWMMMWXKd   xXXWMMMMMWWWWWWWWWWWWWWk   kMx   KMWk   cOXWWWWWW0   kMMx   KWO       dNWo  cNMM
MMXc              kWNc              cKMMMMMk   0MMMMMMMNd                lXMx   KMMWO               OMMx   XMW0     xWMWo  cNMM
MMMMMWWNNNNNNNNNNNWMMMWNNNNNNNNNNNNNNWMMMMMWWNWMMMMMMMMMWNNNNNNNNNNNNNWMMMMMWNNWMMMMMMMMMWWNNNNNNNNWMMMWNNWMMMMMWNNMMMMMWNNWMMM`
);
