# (c) https://github.com/MontiCore/monticore  
stages:
#  - windows
  - linux

masterJobLinux:
  stage: linux
  image: maven:3.5.4-jdk-8-alpine
  script:
    - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
  only:
    - master
  except:
    changes:
    - .gitlab-ci.yml
    - .gitignore
    - README.md

#masterJobWindows:
#  stage: windows
#  script:
#    - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
#  tags:
#    - Windows10
#    - Windows10_OS
#    - Windows10_64bit

BranchJobLinux:
  stage: linux
  image: maven:3.5.4-jdk-8-alpine
  script:
    - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  except:
    - master
