/**
 *
 *  ******************************************************************************
 *  MontiCAR Modeling Family, www.se-rwth.de
 *  Copyright (c) 2017, Software Engineering Group at RWTH Aachen,
 *  All rights reserved.
 *
 *  This project is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3.0 of the License, or (at your option) any later version.
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this project. If not, see <http://www.gnu.org/licenses/>.
 * *******************************************************************************
 */
/* generated by template templates.de.monticore.lang.tagschema.ValuedTagType*/


package taggingTest;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;


/**
 * Created by ValuedTagType.ftl
 */
public class ClassTagSymbol extends TagSymbol {
  public static final ClassTagKind KIND = ClassTagKind.INSTANCE;

  public ClassTagSymbol(String value) {
    super(KIND, value);
  }

  protected ClassTagSymbol(ClassTagKind kind, String value) {
    super(kind, value);
  }

  public String getValue() {
     return getValue(0);
  }

  @Override
  public String toString() {
    return String.format("ClassTag = \"%s\"",
      getValue().toString());
  }

  public static class ClassTagKind extends TagKind {
    public static final ClassTagKind INSTANCE = new ClassTagKind();

    protected ClassTagKind() {
    }
  }
}