# (c) https://github.com/MontiCore/monticore  
stages:
#- windows
- linuxCompile
- integration
- linuxDeploy

#masterJobWindows:
#  stage: windows
#  allow_failure: true
#  script:
#    - call mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean install --settings settings.xml -U
#  tags:
#  - Windows10

CompileJobLinux:
  stage: linuxCompile
  image: maven:3-jdk-8
  artifacts:
    paths:
    - target/
    expire_in: 1 day
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml -U
#  - cat target/site/jacoco/index.html

DeployJobLinux:
  stage: linuxDeploy
  image: maven:3-jdk-8
  dependencies:
    - CompileJobLinux
  script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B deploy --settings settings.xml -U
  only:
  - master

MqttIntegrationJob:
  stage: integration
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2mqtt:v1
  dependencies:
    - CompileJobLinux
  script:
    - chmod 770 ./src/test/bash/integrationTestMqtt.sh
    - ./src/test/bash/integrationTestMqtt.sh

RosIntegrationJob:
  stage: integration
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2middleware/ema-ros-kinetic
  dependencies:
    - CompileJobLinux
  script:
  - ./src/test/bash/integrationTestRos.sh

SomeIPIntegrationJob:
  stage: integration
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2someip:v2
  dependencies:
    - CompileJobLinux
  script:
  - chmod 770 ./src/test/bash/integrationTestSomeIP.sh
  - ./src/test/bash/integrationTestSomeIP.sh

Ros2IntegrationJob:
  stage: integration
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2middleware/ema-ros-crystal
  dependencies:
    - CompileJobLinux
  script:
  - ./src/test/bash/integrationTestRos2.sh
