spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
#  jpa:
#    show-sql:
#      true
#    hibernate:
#      ddl-auto: create
#      format_sql: true

provider:
  url: ${DATA_PROVIDER_URL}

mydata:
  solution: urn:solution:rwth-student-solution
