server:
  error:
    include-message: always

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
#  jpa:
#    show-sql:
#      true
#    hibernate:
#      ddl-auto: create
#      format_sql: true

provider:
  url: ${DATA_PROVIDER_URL}

mydata:
  solution: urn:solution:rwth-student-solution
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create
        hbm2ddl:
          auto: create
  datasource:
    jdbc-url: jdbc:h2:file:~/mydata;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
