server:
  port: ${BACKEND_PORT}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web: DEBUG

provider:
  name: ${PROVIDER_NAME}
  url: ${PROVIDER_URL}

consumer:
  url: ${CONSUMER_URL}
