# (c) https://github.com/MontiCore/monticore
#
image: maven:3-jdk-8

githubjob:
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITHUB_SSH_PRIV_KEY")
  - echo "$GITHUB_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
  - git config --global user.email "kusmenko@se-rwth.de"
  - git config --global user.name "EMA CI Robot"
  - mkdir -p ~/.ssh
#  - cat gitlab-known-hosts >> ~/.ssh/known_hosts
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script: 
  - git clone git@github.com:MontiCore/EmbeddedMontiArc.git
  - cd EmbeddedMontiArc
  - git subtree pull --prefix $PRJ_NAME https://git.rwth-aachen.de/monticore/EmbeddedMontiArc/${PRJ_NAME}.git master --squash
  - git push --force
  only:
  - master

masterJob:
  script: "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install deploy --settings settings.xml"
  only:
  - master
  except:
    changes:
    - README.md
    - .gitlab-ci.yml
    - .gitignore
  
BranchJob:
  script: "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml"
  except:
  - master
