/*
 * (c) https://github.com/MontiCore/monticore
 */
package de.monticore.lang.monticar.sol.plugins.ls.plugin.configuration;

import de.monticore.lang.monticar.sol.plugins.common.plugin.generate.configuration.GeneratePluginConfiguration;

public interface LanguageServerConfiguration extends GeneratePluginConfiguration {
    /**
     * @return The qualified name of the grammar.
     */
    String getGrammarQualifiedName();

    /**
     * @return The name of the grammar.
     */
    String getGrammarName();

    /**
     * @return The package structure of the language infrastructure generated by MontiCore.
     */
    String getGrammarGeneratedPackage();

    /**
     * @return The package structure until the root with the first artifact is reached.
     */
    String getPackageStructure();
}
