#
#
# /* (c) https://github.com/MontiCore/monticore */
#
# The license generally applicable for this project
# can be found under https://github.com/MontiCore/monticore.
#

# (c) https://github.com/MontiCore/monticore  
#

version: "2"

services:
  autopilot:
    image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/rmimodelserver:latest
    restart: always
    entrypoint:
      - java
      - -cp
      - rmi-model-server.jar
      - -Djava.rmi.server.codebase=file:rmi-model-server.jar
      - -Djava.rmi.server.useLocalHostname
      - rwth.rmi.model.server.RMIServer
      - "10101"
      - autopilots
      - --no-zookeeper
      - no_time
      - os=linux

  runner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: simulation-integration-test
    depends_on:
      - autopilot
    volumes:
      - ../:/app
    entrypoint:
      - sh
      - /bin/run_test.sh
