# (c) https://github.com/MontiCore/monticore
stages:
- linux
#- deploy

masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script: 
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
  - cat target/site/jacoco/index.html
  only:
  - master
  
BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script: 
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
  - cat target/site/jacoco/index.html
  except:
  - master

# deploy:
#  stage: deploy
#  image: maven:3-jdk-8
#  script:
#    - "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml"