# (c) https://github.com/MontiCore/monticore

stages:
- linux


TestGLUON:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/mxnet:v0.0.3
  script: 
  - chmod +x build.sh
  - ./build.sh
  - build/src/cpp/ShowAttendTell resources/training_data/plane.jpg resources/training_data/dict.txt

