# (c) https://github.com/MontiCore/monticore  

stages:
#- windows
- linux
- trigger
#- deploy

masterJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script: 
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -U clean deploy --settings settings.xml
  - cat target/site/jacoco/index.html
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "master" 
      changes:
        - src/**/*
        - pom.xml
        - settings.xml
    


  
#masterJobWindows:
#  stage: windows
#  script:
#  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
#  tags:
#  - Windows10
#  except:
#    changes:
#    - README.md
#    - .gitignore
#    - .gitlab-ci.yml


BranchJobLinux:
  stage: linux
  image: maven:3-jdk-8
  script: 
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -U  clean install --settings settings.xml
  - cat target/site/jacoco/index.html
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH != "master" 
      changes:
        - src/**/*
        - pom.xml
        - settings.xml

#deploy:
#  stage: deploy
#  image: maven:3-jdk-8
#  script:
#    - "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml"

trigger-emadl:
  stage: trigger
  trigger:
    project: monticore/EmbeddedMontiArc/generators/EMADL2CPP
    branch: master
  only:
  - master