name: CooperativeAutopilot
on:
  push:
    paths:
      - 'applications/CooperativeAutopilot/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 52201
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.EMA_GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
  GIT_SUBMODULE_STRATEGY: recursive
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  TestSaaS:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp:ema-lab
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp:ema-lab tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/CooperativeAutopilot
            mvn streamtest:streamtest-generator -s settings.xml
            temp-build.sh
            mvn emadl:simulate -s settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

