name: crfrnn
on:
  push:
    paths:
      - 'applications/crfrnn/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 37607
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.EMA_GITLAB_TOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  FileChanges:
    runs-on: ubuntu-latest
    outputs:
      runTestMNIST: ${{steps.TestMNIST.outputs.run}}
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for file changes
        run: |
          CHANGES=$(git diff --name-only HEAD^ HEAD)
          echo "$CHANGES"
          echo "$CHANGES" > diff.txt
      - name: Check TestMNIST
        id: TestMNIST
        run: |
          exc=true
          for path in $(cat diff.txt); do
            if [[ $path == *README.md* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
            if [[ $path == *.gitignore* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
          done
          echo "Final file status except check: $exc"
          echo "run=$exc" >> $GITHUB_OUTPUT
  mnistsmallseg_phase:
    needs: [ TestMNIST ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage mnistsmallseg"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage mnistsmallseg"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}
  unet_phase:
    needs: [ mnistsmallseg_phase, ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage unet"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage unet"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  TestMNIST:
    needs: FileChanges
    if: ${{ !cancelled() && needs.FileChanges.outputs.runTestMNIST == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/mnistcalculator/mxnet:v0.0.3
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} ghcr.io/monticore/mnistcalculator/mxnet:v0.0.3 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/crfrnn
            cd mnistsmallseg
            chmod +x build.sh
            ./build.sh
        run: docker exec build-container bash -c "set -e; $SCRIPT"

