name: Datasets
on:
  push:
    paths:
      - 'applications/Datasets/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID : 57999
  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
jobs:

  deploy-mnist-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-base-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_base
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-base-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_base
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-extension-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_extension
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-extension-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_extension
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-separated-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_separated
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-separated-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_separated
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-vae-mnist-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/vae/vae-mnist
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-vae-mnist-dataset:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/vae/vae-mnist
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-letter-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_letters
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-letter-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_letters
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-cifar-10-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        continue-on-error: true
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/cifar_10
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-cifar-10-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        continue-on-error: true
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/cifar_10
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-operator-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_operators
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-operator-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_operators
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-operator-reduced-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_operators_reduced
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-operator-reduced-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_operators_reduced
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  install-mnist-hexadecimal-dataset:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_hexadecimal
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:install-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  deploy-mnist-hexadecimal-dataset:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/Datasets
            cd datasets/mnist_hexadecimal
            mvn -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.rto=18000000000  emadl:deploy-dataset -s ../ci_settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

