name: doppelkopf-agent
on:
  push:
    paths:
      - 'applications/reinforcement_learning/doppelkopf-agent/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID : 74635
  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
jobs:
  linuxBuildJava17_phase:
    needs: [TestBuildJava17]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Finished stage linuxBuildJava17"
          if: ${{!contains(needs.*.result, 'failure')}}
        - run: |
            echo "Failed stage linuxBuildJava17"
            exit 1
          if: ${{contains(needs.*.result, 'failure')}}
  linuxBuildJava1_8_phase:
    needs: [linuxBuildJava17_phase, TestBuildJava1_8]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Finished stage linuxBuildJava1_8"
          if: ${{!contains(needs.*.result, 'failure')}}
        - run: |
            echo "Failed stage linuxBuildJava1_8"
            exit 1
          if: ${{contains(needs.*.result, 'failure')}}

  TestBuildJava17:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-openjdk-17-slim
    timeout-minutes: 120
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install git -y
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Script
        shell: bash
        run: |
            cd applications/reinforcement_learning/doppelkopf-agent
            apt-get update
            apt-get install software-properties-common -y
            apt-get install -y gnupg2
            echo "deb http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            echo "deb-src http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF8406856DBFCA18
            apt-add-repository ppa:swi-prolog/stable -y 2>/dev/null
            apt-get install -y swi-prolog
            cd doppelkopf-environment
            mvn clean package -s settings.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: TestBuildJava17
          retention-days: 1 week
          path: |
            applications/reinforcement_learning/doppelkopf-agent/doppelkopf-environment/target/

  TestBuildJava1_8:
    needs: [TestBuildJava17, linuxBuildJava17_phase]
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: TestBuildJava17
          path: |
            applications/reinforcement_learning/doppelkopf-agent/applications/reinforcement_learning/doppelkopf-agent/doppelkopf-environment/target/
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/cartpole/rl-fix-new2:latest
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/cartpole/rl-fix-new2:latest tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/reinforcement_learning/doppelkopf-agent
            apt-get update
            apt-get install -y maven
            cp -r ../../../generators/EMAM2Middleware .
            cd EMAM2Middleware
            mvn clean package -s settings.xml -DskipTests
            cd ..
            cp "EMAM2Middleware/target/embedded-montiarc-math-middleware-generator"*"jar-with-dependencies.jar" doppelkopf-agent/embedded-montiarc-math-middleware-generator-jar-with-dependencies.jar
            cd doppelkopf-agent
            chmod 777 *.sh
            ./install.sh
        run: docker exec build-container bash -c "$SCRIPT"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: TestBuildJava1_8
          retention-days: 1 week
          path: |
            applications/reinforcement_learning/doppelkopf-agent/doppelkopf-agent/generator-target/

  TestTrain:
    needs: [TestBuildJava17 , TestBuildJava1_8, linuxBuildJava1_8_phase]
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: TestBuildJava17
          path: |
            applications/reinforcement_learning/doppelkopf-agent/applications/reinforcement_learning/doppelkopf-agent/doppelkopf-environment/target/
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: TestBuildJava1_8
          path: |
            applications/reinforcement_learning/doppelkopf-agent/applications/reinforcement_learning/doppelkopf-agent/doppelkopf-agent/generator-target/
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/cartpole/rl-fix-new2:latest
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/cartpole/rl-fix-new2:latest tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/reinforcement_learning/doppelkopf-agent
            apt-get update
            apt-get install -y maven
            apt-get install -y gnupg2
            echo "deb http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            echo "deb-src http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF8406856DBFCA18
            apt-get update
            apt-get install -y swi-prolog
            apt-get install software-properties-common -y
            add-apt-repository ppa:openjdk-r/ppa -y
            apt-get update
            apt install openjdk-11-jdk -y
            cd doppelkopf-environment
            roscore &
            sleep 2
            java --version
            java -cp "target/doppelkopf-environment-1.4.3-SNAPSHOT.jar" de.gdl.rl.environment.games.doppelkopf.DoppelkopfEnvironment --training &
            echo "wait 5 seconds ..."
            sleep 5
            cd ../doppelkopf-agent
            chmod 777 *.sh
            ./run_training.sh
        run: docker exec build-container bash -c "$SCRIPT"

