name: EMACodeBERT
on:
  push:
    paths:
      - 'applications/EMACodeBERT/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 54873
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.EMA_GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  deploy-pretrained:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.6-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} -e cibuild=$cibuild maven:3.6-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/EMACodeBERT
            cd packaging && mvn emadl:deploy-pretrained -X -s ci_settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

