name: EMAStudioInstaller
on:
  push:
    paths:
      - 'utilities/EMAStudioInstaller/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 20764
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  Linux:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull electronuserland/builder:10
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} electronuserland/builder:10 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/EMAStudioInstaller
            git submodule update --init
            yarn install
            yarn run compile
            yarn run build
            yarn run package
        run: docker exec build-container bash -c "set -e; $SCRIPT"

