name: EmbeddedMontiArcStudio3
on:
  push:
    paths:
      - 'utilities/EmbeddedMontiArcStudio3/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 39210
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  NODE_OPTIONS: --max-old-space-size=4096
concurrency:
  group: branch-${{ github.ref }}
  cancel-in-progress: true
jobs:
  install_phase:
    needs: [ install ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage install"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage install"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  install:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/sol/build:2019.09.26
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} ghcr.io/monticore/sol/build:2019.09.26 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/EmbeddedMontiArcStudio3
            yarn install --ignore-scripts
            mvn -B clean install
            yarn install --ignore-scripts
            cd common
            yarn prepare
        run: docker exec build-container bash -c "$SCRIPT"

  deploy:
    needs: install_phase
    if: ${{ !cancelled() && needs.install_phase.result == 'success' &&  github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/sol/build:2019.09.26
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} ghcr.io/monticore/sol/build:2019.09.26 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/EmbeddedMontiArcStudio3
            yarn install --ignore-scripts
            mvn -B clean install
            yarn install --ignore-scripts --frozen-lockfile
            cd common
            echo "" >> .npmrc
            echo "email=cibuild@se-rwth.de" >> .npmrc
            echo "always-auth=true" >> .npmrc
            echo "_auth=\${cibuildb64}" >> .npmrc
            yarn publish
        run: docker exec build-container bash -c "$SCRIPT"

