name: EmbeddedMontiArcBehaviour
on:
  push:
    paths:
      - 'languages/EmbeddedMontiArcBehaviour/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID : 17654
  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
jobs:
  FileChanges:
    runs-on: ubuntu-latest
    outputs:
      runmasterJob: ${{steps.masterJob.outputs.run}}
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for file changes
        run: |
          CHANGES=$(git diff --name-only HEAD^ HEAD)
          echo "$CHANGES"
          echo "$CHANGES" > diff.txt
      - name: Check masterJob
        id: masterJob
        run: |
          exc=true
          for path in $(cat diff.txt); do
            if [[ $path == *README.md* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
            if [[ $path == *.gitlab-ci.yml* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
            if [[ $path == *.gitignore* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
          done
          echo "Final file status except check: $exc"
          echo "run=$exc" >> $GITHUB_OUTPUT

  masterJob:
    needs: FileChanges
    if: ${{ !cancelled() && github.ref_name == 'master' && needs.FileChanges.outputs.runmasterJob == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/EmbeddedMontiArcBehaviour
            m
            v
            n
             
            -
            D
            o
            r
            g
            .
            s
            l
            f
            4
            j
            .
            s
            i
            m
            p
            l
            e
            L
            o
            g
            g
            e
            r
            .
            l
            o
            g
            .
            o
            r
            g
            .
            a
            p
            a
            c
            h
            e
            .
            m
            a
            v
            e
            n
            .
            c
            l
            i
            .
            t
            r
            a
            n
            s
            f
            e
            r
            .
            S
            l
            f
            4
            j
            M
            a
            v
            e
            n
            T
            r
            a
            n
            s
            f
            e
            r
            L
            i
            s
            t
            e
            n
            e
            r
            =
            w
            a
            r
            n
             
            -
            B
             
             
            c
            l
            e
            a
            n
             
            i
            n
            s
            t
            a
            l
            l
             
            d
            e
            p
            l
            o
            y
             
            -
            -
            s
            e
            t
            t
            i
            n
            g
            s
             
            s
            e
            t
            t
            i
            n
            g
            s
            .
            x
            m
            l
        run: docker exec build-container bash -c "$SCRIPT"

  BranchJob:
    needs: FileChanges
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/EmbeddedMontiArcBehaviour
            m
            v
            n
             
            -
            D
            o
            r
            g
            .
            s
            l
            f
            4
            j
            .
            s
            i
            m
            p
            l
            e
            L
            o
            g
            g
            e
            r
            .
            l
            o
            g
            .
            o
            r
            g
            .
            a
            p
            a
            c
            h
            e
            .
            m
            a
            v
            e
            n
            .
            c
            l
            i
            .
            t
            r
            a
            n
            s
            f
            e
            r
            .
            S
            l
            f
            4
            j
            M
            a
            v
            e
            n
            T
            r
            a
            n
            s
            f
            e
            r
            L
            i
            s
            t
            e
            n
            e
            r
            =
            w
            a
            r
            n
             
            -
            B
             
             
            c
            l
            e
            a
            n
             
            i
            n
            s
            t
            a
            l
            l
             
            -
            -
            s
            e
            t
            t
            i
            n
            g
            s
             
            s
            e
            t
            t
            i
            n
            g
            s
            .
            x
            m
            l
        run: docker exec build-container bash -c "$SCRIPT"

