name: GDL
on:
  push:
    paths:
      - 'languages/GDL/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 60571
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.EMA_GITLAB_TOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_phase:
    needs: [ build ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage build"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage build"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull gradle:6.9.0-jdk11
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} gradle:6.9.0-jdk11 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/GDL
            export GRADLE_USER_HOME=`pwd`/.gradle
            apt-get update
            apt-get install -y gnupg2
            echo "deb http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            echo "deb-src http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF8406856DBFCA18
            apt-get update
            apt-get install -y swi-prolog
            gradle build $GRADLE_OPT $ARGS1 --info
        run: docker exec build-container bash -c "set -e; $SCRIPT"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build
          retention-days: 1 week
          path: |
            languages/GDL/target/
            languages/GDL/.gradle/

  deploy:
    needs: build_phase
    if: ${{ !cancelled() && needs.build_phase.result == 'success' &&  github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull gradle:6.9.0-jdk11
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} gradle:6.9.0-jdk11 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/GDL
            export GRADLE_USER_HOME=`pwd`/.gradle
            apt-get update
            apt-get install -y gnupg2
            echo "deb http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            echo "deb-src http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF8406856DBFCA18
            apt-get update
            apt-get install -y swi-prolog
            gradle publish $GRADLE_OPT $ARGS2 --info
        run: docker exec build-container bash -c "set -e; $SCRIPT"

