name: GDLTools
on:
  push:
    paths:
      - 'utilities/GDLTools/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 69053
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linuxCompile_phase:
    needs: [ CompileJobLinux ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage linuxCompile"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage linuxCompile"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  CompileJobLinux:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.8.3-openjdk-17
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.8.3-openjdk-17 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/GDLTools
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml -U
        run: docker exec build-container bash -c "$SCRIPT"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: CompileJobLinux
          retention-days: 1 day
          path: |
            utilities/GDLTools/target/

  DeployJobLinux:
    needs: [ CompileJobLinux, linuxCompile_phase ]
    if: ${{ !cancelled() && needs.linuxCompile_phase.result == 'success' && needs.CompileJobLinux.result == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: CompileJobLinux
          path: |
            utilities/GDLTools/utilities/GDLTools/target/
      - name: Start Docker Container
        run: |
          docker pull maven:3.8.3-openjdk-17
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3.8.3-openjdk-17 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/GDLTools
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B deploy --settings settings.xml -U
        run: docker exec build-container bash -c "$SCRIPT"

