name: Migrate Docker Images
on:
  workflow_dispatch:
jobs:
  docker-migration:
    runs-on: ubuntu-latest
    env:
      GITLAB_USERNAME: "David.Blum"
      GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Log in to GitLab
        run: |
          docker login registry.git.rwth-aachen.de/ -u "$GITLAB_USERNAME" -p "$GITLABTOKEN"
      - name: Log in to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Migrate Docker images from VisualizationEMAM
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/visualizationemam$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/visualizationemam/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/visualizationemam$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/visualizationemam/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from ViewVerification
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/viewverification$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/viewverification/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/viewverification$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/viewverification/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from Semantics
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/semantics$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/semantics/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/semantics$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/semantics/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from MontiPipes
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/montipipes$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/montipipes/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/montipipes$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/montipipes/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from CNNArch2PyTorch
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/cnnarch2pytorch$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/cnnarch2pytorch/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/cnnarch2pytorch$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/cnnarch2pytorch/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from CNNArch2MXNet
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/cnnarch2mxnet$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/cnnarch2mxnet/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/cnnarch2mxnet$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/cnnarch2mxnet/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from EMAM2Wasm
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2wasm$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emam2wasm/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/emam2wasm$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/emam2wasm/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
