name: Migrate Docker Images
on:
  workflow_dispatch:
jobs:
  docker-migration:
    runs-on: ubuntu-latest
    env:
      GITLAB_USERNAME: "David.Blum"
      GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Log in to GitLab
        run: |
          docker login registry.git.rwth-aachen.de/ -u "$GITLAB_USERNAME" -p "$GITLABTOKEN"
      - name: Log in to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      