name: Migrate Docker Images
on:
  workflow_dispatch:
jobs:
  docker-migration:
    runs-on: ubuntu-latest
    env:
      GITLAB_USERNAME: "David.Blum"
      GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Log in to GitLab
        run: |
          docker login registry.git.rwth-aachen.de/ -u "$GITLAB_USERNAME" -p "$GITLABTOKEN"
      - name: Log in to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Migrate Docker images from Tagging
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/tagging$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/tagging/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/tagging$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/tagging/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from Tagging-Examples
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/tagging-examples$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/tagging-examples/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/tagging-examples$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/tagging-examples/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from Struct
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/struct$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/struct/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/struct$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/struct/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from SchemaLang
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/schemalang$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/schemalang/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/schemalang$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/schemalang/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from MontiMathOpt
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/montimathopt$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/montimathopt/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/montimathopt$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/montimathopt/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from MontiMath
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/montimath$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/montimath/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/montimath$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/montimath/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from languagescommon
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/languagescommon$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/languagescommon/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/languagescommon$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/languagescommon/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from GDL
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/gdl$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/gdl/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/gdl$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/gdl/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from Enum
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/enum$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/enum/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/enum$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/enum/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from EmbeddedMontiView
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiview$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiview/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiview$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiview/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from EmbeddedMontiArcMath
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcmath$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcmath/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarcmath$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarcmath/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from EmbeddedMontiArc
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarc$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarc/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarc$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarc/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from EmbeddedMontiArcBehaviour
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcbehaviour$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcbehaviour/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarcbehaviour$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarcbehaviour/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from EmbeddedMontiArcApplication
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcapplication$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/languages/embeddedmontiarcapplication/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarcapplication$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/embeddedmontiarcapplication/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
