name: Migrate Docker Images
on:
  workflow_dispatch:
jobs:
  docker-migration:
    runs-on: ubuntu-latest
    env:
      GITLAB_USERNAME: "David.Blum"
      GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Log in to GitLab
        run: |
          docker login registry.git.rwth-aachen.de/ -u "$GITLAB_USERNAME" -p "$GITLABTOKEN"
      - name: Log in to GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Migrate Docker images from SimulationLanguage
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/simulationlanguage$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/simulationlanguage/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/simulationlanguage$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/simulationlanguage/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from simulation
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/simulation$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/simulation/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/simulation$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/simulation/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from hardware_emulator
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/hardware_emulator$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/hardware_emulator/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/hardware_emulator$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/hardware_emulator/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from Documentation
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/documentation$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/documentation/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/documentation$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/documentation/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from commons
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/commons$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/commons/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/commons$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/commons/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from basic-simulator
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/basic-simulator$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/basic-simulator/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/basic-simulator$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/basic-simulator/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
      - name: Migrate Docker images from AutopilotTools
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IFS="," read -ra IMAGES <<< ""
          for IMAGE in "${IMAGES[@]}"; do
            if [[ $IMAGE == :* ]]; then
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/autopilottools$IMAGE"
            else
              GITLAB_IMAGE="registry.git.rwth-aachen.de/monticore/embeddedmontiarc/simulators/autopilottools/$IMAGE"
            fi
            LOWERCASE_IMAGE=$(echo "$IMAGE" | tr "[:upper:]" "[:lower:]")
            if [[ $IMAGE == :* ]]; then
              GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/autopilottools$LOWERCASE_IMAGE"
            else
               GHCR_IMAGE="ghcr.io/$LOWERCASE_OWNER/autopilottools/$LOWERCASE_IMAGE"
            fi
            echo "Pulling image from GitLab: $GITLAB_IMAGE"
            docker pull "$GITLAB_IMAGE"
            echo "Tagging image for GHCR: $GHCR_IMAGE"
            docker tag "$GITLAB_IMAGE" "$GHCR_IMAGE"
            echo "Pushing image to GHCR: $GHCR_IMAGE"
            docker push "$GHCR_IMAGE"
            echo "Removing local image: $GHCR_IMAGE"
            docker rmi -f $(docker images -q) || true
          done
