name: kipf-gnn
on:
  push:
    paths:
      - 'applications/kipf-gnn/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 64545
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  TestCoraCustomNetwork:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170:v0.0.1
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170:v0.0.1 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/kipf-gnn
            ln /usr/bin/python3 /usr/bin/python -f
            python -m pip install -U pip
            python -m pip install scikit-image
            python -m pip install opencv-python
            mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
            cd cora-custom-gnn
            mvn dependency:resolve emadl:train -s settings.xml -U
        run: docker exec build-container bash -c "set -e; $SCRIPT"

  TestCoraDglNetwork:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/kipf-gnn
            ln /usr/bin/python3 /usr/bin/python -f
            python -m pip install -U pip
            python -m pip install scikit-image
            python -m pip install opencv-python
            mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
            export DGLBACKEND=mxnet
            cd cora-dgl-gnn
            mvn dependency:resolve emadl:train -s settings.xml -U
        run: docker exec build-container bash -c "set -e; $SCRIPT"

  TestCuboidDglNetwork:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/kipf-gnn
            ln /usr/bin/python3 /usr/bin/python -f
            python -m pip install -U pip
            python -m pip install scikit-image
            python -m pip install opencv-python
            mv /mxnet/build/libmxnet.so /mxnet/build/libmxnet.a /usr/lib/
            export DGLBACKEND=mxnet
            cd cuboid-dgl-gnn
            mvn dependency:resolve emadl:train -s settings.xml -U
        run: docker exec build-container bash -c "set -e; $SCRIPT"

