name: letter-predictor
on:
  push:
    paths:
      - 'applications/letter-predictor/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID : 81183
  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
jobs:

  TestLetterPredictor:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/mxnet/190:v0.0.2
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/mxnet/190:v0.0.2 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/letter-predictor
            apt update && apt install -y libomp-dev
            python3 -m pip install -U pip
            python3 -m pip install scikit-image opencv-python
            mvn dependency:resolve emadl:train -s settings.xml -U
        run: docker exec build-container bash -c "$SCRIPT"

