name: LifelongLanguageLearning
on:
  push:
    paths:
      - 'applications/LifelongLanguageLearning/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 47624
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.EMA_GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  TestLifeongLanguageLearningTraining:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170:v0.0.1
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170:v0.0.1 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/LifelongLanguageLearning
            cd lifelong-language-learning
            mvn streamtest:streamtest-build -s settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

  TestLifeongLanguageLearningPrediction:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170:v0.0.1
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/dockerimages/mxnet170:v0.0.1 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/LifelongLanguageLearning
            cd gluon
            chmod +x build.sh
            ./build.sh
            RES=$(./build/src/cpp/LifelongLanguageLearning resources/prediction_data/prediction_samples.txt resources/prediction_data/prediction_sequences.txt resources/prediction_data/prediction_lengths.txt)
            if [[ $RES != *"Prediction for sample 0: 0"* ]]; then echo "Wrong result:" $RES; exit 1; fi;
        run: docker exec build-container bash -c "set -e; $SCRIPT"

