name: maven-streamtest
on:
  push:
    paths:
      - 'utilities/maven-streamtest/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 17752
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
jobs:
  linux_phase:
    needs: [ BranchJobLinux, masterJobLinux ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage linux"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage linux"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  masterJobLinux:
    if: ${{ !cancelled() && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/mxnet/190:latest
          docker run --name build-container -d -v $(pwd)/utilities/maven-streamtest:/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/mxnet/190:latest tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

  trigger-project:
    needs: linux_phase
    if: ${{ !cancelled() && needs.linux_phase.result == 'success' &&  github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    continue-on-error: true
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Record trigger time
        id: trigger_time
        run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: Trigger emadl-maven-plugin pipeline
        run: gh workflow run $WORKFLOW_FILE --repo $REPO  --ref $BRANCH
        env:
          WORKFLOW_FILE: emadl-maven-plugin.yml
          BRANCH: ${{ github.ref_name }}
          REPO: ${{github.repository}}
          GH_TOKEN: ${{github.token}}
      - name: Wait for workflow to appear
        run: sleep 20
      - name: Get latest run ID of Child Workflow after trigger time
        id: get_run
        run: |
          RUN_ID=$(gh run list --workflow=$WORKFLOW_FILE --branch=$BRANCH --repo=$REPO --json databaseId,createdAt \
          --jq '[.[] | select(.createdAt > "${{ steps.trigger_time.outputs.time }}")] | sort_by(.createdAt) | last.databaseId')
          echo "Run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{github.token}}
          WORKFLOW_FILE: emadl-maven-plugin.yml
          BRANCH: ${{ github.ref_name }}
          REPO: ${{github.repository}}
      - name: Wait for Child Workflow to finish
        run: |
          while true; do
            STATUS=$(gh run view "${{ steps.get_run.outputs.run_id }}" --repo=$REPO --json status --jq '.status')
            echo "Current status: $STATUS"
            if [[ "$STATUS" == "completed" ]]; then
              break
            fi
            sleep 60
          done
        env:
          GH_TOKEN: ${{github.token}}
          REPO: ${{github.repository}}
      - name: Check Child Workflow result
        continue-on-error: true
        run: |
          RESULT=$(gh run view "${{ steps.get_run.outputs.run_id }}" --repo=$REPO --json conclusion --jq '.conclusion')
          echo "Child Workflow result: $RESULT"
          if [[ "$RESULT" != "success" ]]; then
            echo "Child Workflow failed"
            exit 1
          fi
        env:
          GH_TOKEN: ${{github.token}}
          REPO: ${{github.repository}}

  BranchJobLinux:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/emadl2cpp/mxnet/190:latest
          docker run --name build-container -d -v $(pwd)/utilities/maven-streamtest:/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild ghcr.io/monticore/emadl2cpp/mxnet/190:latest tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
        run: docker exec build-container bash -c "$SCRIPT"

