name: migrationTool
on:
  push:
    paths:
      - 'utilities/migrationTool/**'
  workflow_dispatch:
concurrency:
  group: branch-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            utilities/migrationTool
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Hatchling
        run: pip install hatchling
      - name: Build migrationTool
        run: |
          cd utilities/migrationTool/
          hatchling build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: utilities/migrationTool/dist/
  test-install:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pipx
        run: python -m pip install pipx
      - name: Install package with pipx
        run: |
          PKG_WHL=$(ls dist/*.whl | head -n1)
          pipx install "$PKG_WHL"
      - name: Test migrationTool
        run: |
          migrationTool --help
