name: migrationTool
on:
  push:
    paths:
      - 'utilities/migrationTool/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          cd utilities/migrationTool
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/utilities/migrationTool/src:$PYTHONPATH" >> $GITHUB_ENV
      - name: Configurate Git
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "Test"
      - name: Run tests
        run: |
          cd utilities/migrationTool
          pip install pytest pytest-cov
          pytest --cov=src/migrationTool --cov-report=term --junitxml=report.xml
      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: always() # ensures this runs even if previous step fails
        with:
          name: Pytest Results
          path: utilities/migrationTool/report.xml
          reporter: java-junit     
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            utilities/migrationTool
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install Hatchling
        run: pip install hatchling
      - name: Build migrationTool
        run: |
          cd utilities/migrationTool/
          hatchling build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: utilities/migrationTool/dist/
  test-install:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pipx
        run: python -m pip install pipx
      - name: Install package with pipx
        run: |
          PKG_WHL=$(ls dist/*.whl | head -n1)
          pipx install "$PKG_WHL"
      - name: Test migrationTool
        run: |
          migrationTool --help
