name: misc
on:
  push:
    paths:
      - 'utilities/misc/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 33335
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLAB_TOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test_phase:
    needs: [ ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage test"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage test"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  masterJobLinux:
    needs: test_phase
    if: ${{ !cancelled() && needs.test_phase.result == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLAB_TOKEN }} maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/misc
            echo "hello world123"
        run: docker exec build-container bash -c "set -e; $SCRIPT"

