name: MontiPipes
on:
  push:
    paths:
      - 'generators/MontiPipes/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 75161
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux_phase:
    needs: [ BranchJobLinux ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage linux"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage linux"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  masterJobLinux:
    needs: linux_phase
    if: ${{ !cancelled() && needs.linux_phase.result == 'success' &&  github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLAB_TOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd generators/MontiPipes
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

  BranchJobLinux:
    if: ${{ github.ref_name != 'main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLAB_TOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd generators/MontiPipes
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

