name: MontiMathOpt
on:
  push:
    paths:
      - 'languages/MontiMathOpt/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 17642
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  FileChanges:
    runs-on: ubuntu-latest
    outputs:
      runmasterJobLinux: ${{steps.masterJobLinux.outputs.run}}
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for file changes
        run: |
          CHANGES=$(git diff --name-only HEAD^ HEAD)
          echo "$CHANGES"
          echo "$CHANGES" > diff.txt
      - name: Check masterJobLinux
        id: masterJobLinux
        run: |
          exc=true
          for path in $(cat diff.txt); do
            if [[ $path == *.gitlab-ci.yml* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
            if [[ $path == *README.md* ]]; then
              echo "Matching path found: $path"
              echo "DONT RUN"
              exc=false
              break
            fi
          done
          echo "Final file status except check: $exc"
          echo "run=$exc" >> $GITHUB_OUTPUT

  masterJobLinux:
    needs: FileChanges
    if: ${{ !cancelled() && github.ref_name == 'master' && needs.FileChanges.outputs.runmasterJobLinux == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/MontiMathOpt
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

  BranchJobLinux:
    needs: FileChanges
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/MontiMathOpt
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

