name: rnnsearch_translator
on:
  push:
    paths:
      - 'applications/rnnsearch_translator/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID : 28688
  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/mnistcalculator/mxnet:v0.0.3
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} ghcr.io/monticore/mnistcalculator/mxnet:v0.0.3 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/rnnsearch_translator
            chmod +x build.sh
            ./build.sh
            ./build/src/cpp/Translator resources/vocabularies/vocab.en resources/vocabularies/vocab.vi 'I am fine .'
        run: docker exec build-container bash -c "$SCRIPT"

