name: SchemaLang
on:
  push:
    paths:
      - 'languages/SchemaLang/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 55667
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
  MAVEN_OPTS: -Xmx4096m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_phase:
    needs: [ build ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage build"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage build"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}
  test_phase:
    needs: [ build_phase, ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage test"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage test"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}
  report_phase:
    needs: [ test_phase, ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage report"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage report"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3.5.4-jdk-8-alpine
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLAB_TOKEN }} -e cibuild=$cibuild maven:3.5.4-jdk-8-alpine tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/SchemaLang
            mvn $MAVEN_CLI_OPTS clean install -U
        run: docker exec build-container bash -c "set -e; $SCRIPT"
      - name: Reporting
        uses: dorny/test-reporter@v2
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: build
          path: |
            languages/SchemaLang/target/surefire-reports/TEST-*.xml
          reporter: java-junit

  deploy:
    needs: report_phase
    if: ${{ !cancelled() && needs.report_phase.result == 'success' &&  github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull maven:3-jdk-8
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLAB_TOKEN }} -e cibuild=$cibuild maven:3-jdk-8 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd languages/SchemaLang
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"

