name: Sol
on:
  push:
    paths:
      - 'utilities/Sol/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 31332
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.EMA_GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  NODE_OPTIONS: --max-old-space-size=4096
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  install_phase:
    needs: [ install ]
    if: ${{ !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Finished stage install"
        if: ${{!contains(needs.*.result, 'failure')}}
      - run: |
          echo "Failed stage install"
          exit 1
        if: ${{contains(needs.*.result, 'failure')}}

  install:
    if: ${{ github.ref_name != 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/sol/build:2019.09.26
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} -e cibuild=$cibuild ghcr.io/monticore/sol/build:2019.09.26 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/Sol
            apt-get update && apt-get install -y build-essential
            yarn install --ignore-scripts
            mvn -B clean install --settings configs/settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"
      - name: Reporting
        uses: dorny/test-reporter@v2
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: install
          path: |
            utilities/Sol/*/*/*/target/surefire-reports/TEST-*.xml
          reporter: java-junit

  pages:
    needs: install_phase
    if: ${{ !cancelled() && needs.install_phase.result == 'success' &&  github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/sol/build:2019.09.26
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.EMA_GITLAB_TOKEN }} -e cibuild=$cibuild ghcr.io/monticore/sol/build:2019.09.26 tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/Sol
            apt-get update && apt-get install -y build-essential
            yarn install --ignore-scripts
            mvn -B clean install --settings configs/settings.xml
            mvn -B deploy sonar:sonar -DskipTests -Dmaven.install.skip=true --settings configs/settings.xml
        run: docker exec build-container bash -c "set -e; $SCRIPT"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: pages
          retention-days: 7
          path: |
            utilities/Sol/public

