name: TopologyOptimizer
on:
  push:
    paths:
      - 'applications/reinforcement_learning/TopologyOptimizer/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 70646
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  TestBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker pull ghcr.io/monticore/cartpole/rl-fix-new2:latest
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLABTOKEN }} ghcr.io/monticore/cartpole/rl-fix-new2:latest tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd applications/reinforcement_learning/TopologyOptimizer
            apt-get update
            apt-get install -y maven
            cp -r ../../../generators/EMAM2Middleware .
            cd EMAM2Middleware
            mvn clean install -s settings.xml
            cd target
            xargs -n 1 cp -v *-jar-with-dependencies.jar<<<"../../topologyoptimizer/cluster/rl/bin/"
            cd ../../topologyoptimizer/cluster/rl/
            chmod +x install.sh
            ./install.sh
        run: docker exec build-container bash -c "set -e; $SCRIPT"

