name: vscode-ema-linter
on:
  push:
    paths:
      - 'utilities/vscode-ema-linter/**'
  workflow_dispatch:
  pull_request:
env:
  CI_PROJECT_ID: 36190
  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
  GITLABTOKEN: ${{ secrets.GITLAB_TOKEN }}
  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  LinuxBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start Docker Container
        run: |
          docker pull node:latest
          docker run --name build-container -d -v $(pwd):/workspace --network=host  -e CI_PROJECT_ID=$CI_PROJECT_ID -e CI_API_V4_URL=$CI_API_V4_URL -e GITLABTOKEN=${{ secrets.GITLAB_TOKEN }} -e cibuild=$cibuild node:latest tail -f /dev/null
      - name: Script
        env:
          SCRIPT: |
            cd /workspace
            cd utilities/vscode-ema-linter
            ./build.sh
        run: docker exec build-container bash -c "set -e; $SCRIPT"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: LinuxBuild
          retention-days: 8 weeks
          path: |
            utilities/vscode-ema-linter/ema-linter.vsix

