# (c) https://github.com/MontiCore/monticore  
stages:
- linux

masterJobLinux:
  stage: linux
  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/end2enddriving
  script:
  - cd tensorflow
  - ./build.sh
  - python3 v-tool/cli.py -i resources/training_data/test.h5 -p